[build-system]
requires = [
  "setuptools >= 40.6.0",
  "wheel",
  "numpy >= 1.23.5",
  "pytest",
  "pandas >= 2.0",
  "pyarrow >= 15.0",
  "pyyaml >= 6.0",
  "chardet >= 5.2",
  "rich >= 13.3",
  "regex >= 2.5.148",
  "tomli_w >= 1.2.0",
  "tomli >= 2.0",
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.8"
name = "tdda"
authors = [
    { name = "Nick Radcliffe", email = "njr@stochasticsolutions.com" },
]
dynamic=["version", "scripts", "dependencies", "keywords", "license", "readme"]

description = "Test-driven data analysis: command-line tools and Python APIs for data validation, testing analytical pipelines, automatic test generation and more."


[tool.pytest.ini_options]
pythonpath = [
  ".", "tdda"
]

#testpaths = [
    #"tdda/serial",
#]

norecursedirs = [
    'constraints',
    'deprecated',
    'doc',
    'pd',
    'gentest',
    'rexpy',
    'serial',
    'referencetest',
    'build'
]

[tool.black]
line-length = 79
skip-string-normalization = true
include = '\.pyi?$'

[tool.ruff]
line-length = 79
exclude = [
    "tdda/serial/testdata",
    "tdda/serial/examples",
    "tdda/serial/examples2",
    "tdda/serial/accounts_examples",
    "tdda/referencetest/testdata",
    "tdda/referencetest/examples",
    "tdda/referencetest/diffexamples",
    "tdda/constraints/testexamples",
    "tdda/constraints/examples",
    "tdda/rexpy/examples",
]

[tool.ruff.format]
line-ending = "auto"
quote-style = "single"
