# -*- coding: utf-8 -*-

"""This module provides the
:py:class:`~tdda.referencetest.referencetestcase.ReferenceTestCase` class,
which extends the
standard :py:class:`unittest.TestCase` test-case class, augmenting it
with methods for checking correctness of files against reference data.

It also provides a ``main()`` function, which can be used to run (and
regenerate) reference tests which have been implemented using subclasses
of ``ReferenceTestCase``.

For example::

    from tdda.referencetest import ReferenceTestCase
    import my_module

    class TestMyClass(ReferenceTestCase):
        def test_my_csv_function(self):
            result = my_module.my_csv_function(self.tmp_dir)
            self.assertCSVFileCorrect(result, 'result.csv')

        def test_my_pandas_dataframe_function(self):
            result = my_module.my_dataframe_function()
            self.assertDataFrameCorrect(result, 'result.csv')

        def test_my_table_function(self):
            result = my_module.my_table_function()
            self.assertStringCorrect(result, 'table.txt', kind='table')

        def test_my_graph_function(self):
            result = my_module.my_graph_function()
            self.assertStringCorrect(result, 'graph.txt', kind='graph')

    TestMyClass.set_default_data_location('testdata')

    if __name__ == '__main__':
        ReferenceTestCase.main()

Tagged Tests
~~~~~~~~~~~~

If the tests are run with the ``--tagged`` or ``-1`` (the digit one)
command-line option, then only tests that have been decorated with
``referencetest.tag``, are run. This is a mechanism for allowing
only a chosen subset of tests to be run, which is useful during
development. The ``@tag`` decorator can be applied to either test
classes or test methods.

If the tests are run with the ``--istagged`` or ``-0`` (the digit
zero) command-line option, then no tests are run; instead, the
framework reports the full module names of any test classes that have
been decorated with ``@tag``, or which contain any tests that have been
decorated with ``@tag``.

For example::

    from tdda.referencetest import ReferenceTestCase, tag
    import my_module

    class TestMyClass1(ReferenceTestCase):
        @tag
        def test_a(self):
            ...

        def test_b(self):
            ...

    @tag
    class TestMyClass2(ReferenceTestCase):
        def test_x(self):
            ...

        def test_y(self):
            ...

If run with ``python mytests.py --tagged``, only the tagged tests are
run (``TestMyClass1.test_a``, ``TestMyClass2.test_x`` and
``TestMyClass2.test_y``).

The ``-9`` (or ``--untag``) option removes all ``@tag`` decorators from
test source files, allowing a clean slate.

Failure Logging and Auto-tagging
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Running with ``-F`` (or ``--log-failures``) causes the names of any
failing or erroring tests to be logged to a file. After the run,
the ``tdda tag`` command reads that log and adds ``@tag`` decorators
to the failing tests automatically.

A typical ``unittest``-style workflow for focusing on failures is:

.. code-block:: bash

    python tests.py -9      # Remove any existing @tag decorators
    python tests.py -F      # Run tests, logging failures
    tdda tag                # Add @tag to failing tests
    python tests.py -1      # Run only tagged (failing) tests

When all tests pass, clean up the tags:

.. code-block:: bash

    python tests.py -9

The equivalent workflow with ``pytest``:

.. code-block:: bash

    pytest --untag          # Remove any existing @tag decorators
    pytest --log-failures   # Run tests, logging failures
    tdda tag                # Add @tag to failing tests
    pytest --tagged         # Run only tagged (failing) tests

When all tests pass, clean up the tags:

.. code-block:: bash

    pytest --untag

Regeneration of Results
~~~~~~~~~~~~~~~~~~~~~~~

When its main is run with ``--write-all`` or ``--write`` (or ``-W`` or ``-w``
respectively), it causes the framework to regenerate reference data
files. Different kinds of reference results can be regenerated by
passing in a comma-separated list of ``kind`` names immediately after
the ``--write`` option. If no list of ``kind`` names is provided, then all
test results will be regenerated.

To regenerate all reference results (or generate them for the first time)

.. code-block:: bash

   pytest -s --write-all

To regenerate just a particular kind of reference (e.g. table results)

.. code-block:: bash

    python my_tests.py --write table

To regenerate a number of different kinds of reference (e.g. both table
and graph results)

.. code-block:: bash

    python my_tests.py --write table graph

"""

import datetime
import glob
import json
import os
import re
import sys
import unittest

from tdda.state import get_testing, set_testing, get_config
from tdda.referencetest.referencetest import (
    ReferenceTest,
    tag,
    DEFAULT_FAIL_DIR,
)
from tdda.utils import TDDAError, nvl, plural


class ReferenceTestCase(unittest.TestCase, ReferenceTest):
    """
    Wrapper around the
    :py:class:`~tdda.referencetest.referencetest.ReferenceTest`
    class to allow it to operate as a test-case class using the
    ``unittest`` testing framework.

    The ``ReferenceTestCase`` class is a mix-in of
    :py:class:`unittest.TestCase`
    and :py:class:`~tdda.referencetest.referencetest.ReferenceTest`,
    so it can be used as the base class for unit tests, allowing the
    tests to use any of the standard ``unittest`` *assert* methods,
    and also use any of the ``referencetest`` *assert* extensions.
    """

    tag = tag

    def __init__(self, *args, **kwargs):
        # Initializer for a ReferenceTestCase instance.
        # This is called automatically by the ``unittest`` runtime framework.
        unittest.TestCase.__init__(self, *args, **kwargs)
        ReferenceTest.__init__(self, self.assertTrue)

    @staticmethod
    def main(module=None, argv=None, testtdda=False, report=None, **kw):
        """
        Wrapper around the :py:func:`unittest.main()` entry point.

        This is the same as the :py:func:`~tdda.referencetestcase.main()`
        function, and is provided just as a convenience, as it means that
        tests using the ``ReferenceTestCase`` class only need to import
        that single class on its own.
        """
        argv, tagged, check, r, untag, log_failures = _set_flags_from_argv(
            argv
        )
        report = nvl(r, report)
        if 'TDDAREPORT' in os.environ:
            report = True
        if testtdda:
            saved = set_testing(True)
        try:
            _run_tests(
                module=module,
                argv=argv,
                tagged=tagged,
                check=check,
                report=report,
                untag=untag,
                log_failures=log_failures,
                **kw,
            )
        finally:
            if testtdda:
                if saved is not None:
                    set_testing(saved)


def _run_tests(
    module=None,
    argv=None,
    tagged=False,
    check=False,
    report=None,
    untag=False,
    log_failures=None,
    **kw,
):
    """
    Run tests
    """
    if untag:
        _untag_tests(module=module, argv=argv)
        return
    if argv is None:
        argv = sys.argv
    loader = (
        TaggedTestLoader(check)
        if tagged or check
        else unittest.defaultTestLoader
    )
    if module is None:
        t = unittest.main(argv=argv, testLoader=loader, exit=False, **kw)
        result = t.__dict__['result']
        module = t.__dict__['module']
        path = getattr(module, '__file__', None)
        if path:
            outpath = os.path.splitext(path)[0] + '-results.json'
            ok = result.failures == result.errors == []
            d = {
                'date': datetime.datetime.now().isoformat(
                    sep='t', timespec='seconds'
                ),
                'run': result.testsRun,
                'failures': len(result.failures),
                'errors': len(result.errors),
                'skipped': len(result.skipped),
                'result': 'PASS' if ok else 'FAIL',
            }
        if report:
            with open(outpath, 'w') as f:
                json.dump(d, f)
        if log_failures is None:
            log_failures = get_config(None).referencetest.log_failures
        if log_failures:
            _record_failing_tests(result)
        sys.exit(0 if ok else 1)
    else:
        unittest.main(module=module, argv=argv, testLoader=loader, **kw)


def _set_flags_from_argv(argv=None):
    """
    This is used to set the class's write flag if a **-write** or
    **--write-all** (or **-W** or **-w**) option is passed on the
    command line, either using the argv provided,
    or :py:data:`sys.argv` otherwise.

    The **-write-all** (or **-W**) option takes no parameters, and turns on
    reference-regeneration for all kinds of results.

    The **-write** (or **-w**) option takes a list of parameter, consisting
    of names of result kinds to be regenerated. The names can be separate
    parameters, or they can be a single comma-separated parameter.

    The framework reports on each file being regenerated, by default. Use
    The **-wquiet** option to make it rewrite files quietly.

    The **--wquiet** option causes files to be rewritten silently.

    If the **-1** or **--tagged** option is set, then only run tagged tests.

    If the **-0** or **--check** option is set, then only report tagged tests,
    without running them.

    A tuple is returned, containing ``argv`` or :py:data:`sys.argv`, with
    any of the *rewrite*, *tagged* or *check* options options removed,
    plus the *tagged* and *checked* state.
    """
    if argv is None:
        argv = sys.argv
    rest = argv[1:]
    tagged = False
    check = False
    regenerate = False
    report = None
    untag = False
    log_failures = None

    for i, arg in enumerate(rest):
        if arg.startswith('-') and not arg.startswith('--'):
            for flag in arg[1:]:
                if flag == 'W':
                    regenerate = True
                    arg = arg.replace('W', '')
                elif flag == '1':
                    tagged = True
                    arg = arg.replace('1', '')
                elif flag == '0':
                    check = True
                    arg = arg.replace('0', '')
                elif flag == '9':
                    untag = True
                    arg = arg.replace('9', '')
                elif flag == 'F':
                    log_failures = True
                    arg = arg.replace('F', '')
                elif flag == 'r':
                    report = True
                    arg = arg.replace('r', '')
                elif flag == 'P':
                    ReferenceTestCase.set_defaults(norm_paths=True)
                    arg = arg.replace('P', '')
            rest[i] = '' if arg == '-' else arg
        else:
            break
    rest = [a for a in rest if a]

    for quietflag in ('-wquiet', '--wquiet'):
        if quietflag in rest:
            idx = rest.index(quietflag)
            ReferenceTestCase.set_defaults(verbose=False)
            rest = rest[:idx] + rest[idx + 1 :]

    for writeflag in ('--W', '--write-all'):
        if writeflag in rest:
            idx = rest.index(writeflag)
            if idx:
                regenerate = True
                rest = rest[:idx] + rest[idx + 1 :]
                break

    for reportflag in ('-report', '--report'):
        if reportflag in rest:
            idx = rest.index(reportflag)
            report = True
            rest = rest[:idx] + rest[idx + 1 :]

    for writeflag in ('-w', '--w', '--write'):
        if writeflag in rest:
            idx = rest.index(writeflag)
            if idx:
                if idx < len(rest) - 1:
                    for r in rest[idx + 1 :]:
                        for kind in r.split(','):
                            ReferenceTestCase.set_regeneration(kind)
                else:
                    raise TDDAError(
                        '--write option requires parameters; '
                        'use --write-all to regenerate all '
                        'reference results'
                    )
            rest = rest[:idx]
            break

    for option in ('--tagged', '--istagged'):
        if option in rest:
            idx = rest.index(option)
            rest = rest[:idx] + rest[idx + 1 :]
            if option in ('-0', '--istagged'):
                check = True
            else:
                    tagged = True

    if '--untag' in rest:
        idx = rest.index('--untag')
        rest = rest[:idx] + rest[idx + 1 :]
        untag = True

    if '--log-failures' in rest:
        idx = rest.index('--log-failures')
        rest = rest[:idx] + rest[idx + 1 :]
        log_failures = True

    if '--no-log-failures' in rest:
        idx = rest.index('--no-log-failures')
        rest = rest[:idx] + rest[idx + 1 :]
        log_failures = False  # explicitly suppressed

    if '--path-norm' in rest:
        idx = rest.index('--path-norm')
        rest = rest[:idx] + rest[idx + 1 :]
        ReferenceTestCase.set_defaults(norm_paths=True)

    if regenerate:
        ReferenceTestCase.set_regeneration()
    return (argv[:1] + rest, tagged, check, report, untag, log_failures)


def _untag_tests(module=None, argv=None):
    """
    Remove @tag decorators from all tagged test source files.
    Finds the source files by loading tagged tests (as -0 does),
    then rewrites each file with @tag lines stripped.
    """
    if argv is None:
        argv = sys.argv
    collected = []
    loader = TaggedTestLoader(check=True, printer=collected.append)
    if module is None:
        unittest.main(argv=argv[:1], testLoader=loader, exit=False)
    else:
        loader.loadTestsFromModule(module)

    source_files = set()
    for classname in collected:
        module_name = classname.rsplit('.', 1)[0]
        mod = sys.modules.get(module_name)
        if mod and getattr(mod, '__file__', None):
            source_files.add(os.path.abspath(mod.__file__))

    for filepath in sorted(source_files):
        _remove_tag_lines(filepath)


def _remove_tag_lines(filepath):
    """Remove all @tag decorator lines from a source file."""
    with open(filepath) as f:
        lines = f.readlines()
    new_lines = [line for line in lines if line.strip() != '@tag']
    n_removed = len(lines) - len(new_lines)
    if n_removed:
        with open(filepath, 'w') as f:
            f.write(''.join(new_lines))
        print(
            'Removed %s from %s'
            % (plural(n_removed, '@tag decorator'), filepath)
        )
    else:
        print('No @tag decorators found in %s' % filepath)


def _record_failing_tests(result):
    """
    Write the IDs of failing/erroring tests to a file in TDDA_FAIL_DIR,
    one per line in the format:
        /abs/path/to/test_file.py::ClassName::test_method_name
        /abs/path/to/test_file.py::test_function_name
    """
    cases = [t for (t, _) in result.failures + result.errors]
    if not cases:
        return
    lines = []
    for test in cases:
        test_id = test.id()  # e.g. "pkg.module.ClassName.test_method"
        parts = test_id.rsplit('.', 2)
        if len(parts) == 3:
            module_name, class_name, method_name = parts
        elif len(parts) == 2:
            module_name, method_name = parts
            class_name = None
        else:
            continue
        mod = sys.modules.get(module_name)
        if mod and getattr(mod, '__file__', None):
            filepath = os.path.abspath(mod.__file__)
            if class_name:
                lines.append(
                    '%s::%s::%s' % (filepath, class_name, method_name)
                )
            else:
                lines.append('%s::%s' % (filepath, method_name))
    if lines:
        stamp = datetime.datetime.now().strftime('%Y-%m-%dT%H%M%S')
        filename = '%s-failing-tests.txt' % stamp
        outpath = os.path.join(DEFAULT_FAIL_DIR, filename)
        with open(outpath, 'w') as f:
            f.write('\n'.join(lines) + '\n')
        print('Failing tests written to %s' % outpath)


def tag_failing_tests(args=None):
    """
    Read a failing-tests file (written by a previous run with -F /
    --tagfailures) and add @tag decorators to each failing test method
    in its source file.

    args: list of command-line arguments; if non-empty, args[0] is the
          path to the failing-tests file.  If empty/None, finds the most
          recent `*-failing-tests.txt` file in $TDDA_FAIL_DIR.
    """
    if args:
        filepath = args[0]
    else:
        pattern = os.path.join(
            DEFAULT_FAIL_DIR, '????-??-??T??????-failing-tests.txt'
        )
        candidates = sorted(glob.glob(pattern))
        if not candidates:
            print('No failing tests file found in %s' % DEFAULT_FAIL_DIR)
            return
        filepath = candidates[-1]
    if not os.path.exists(filepath):
        print('No failing tests file found at %s' % filepath)
        return
    with open(filepath) as f:
        lines = [l.strip() for l in f if l.strip()]
    by_file = {}
    for line in lines:
        parts = line.split('::')
        src = parts[0]
        identifiers = parts[1:]  # [ClassName, method] or [function_name]
        by_file.setdefault(src, []).append(identifiers)
    for src, items in sorted(by_file.items()):
        _add_tag_lines(src, items)


def _add_tag_lines(filepath, items):
    """
    Add @tag decorators to the specified test methods/functions in filepath.

    items is a list of:
        [class_name, method_name]  — for a method inside a class
        [function_name]            — for a module-level test function
    """
    with open(filepath) as f:
        lines = f.readlines()

    # Ensure `tag` is imported; fix the import line if needed
    tag_imported = any(re.search(r'\bimport\b.*\btag\b', l) for l in lines)
    if not tag_imported:
        for i, line in enumerate(lines):
            m = re.match(r'(from\s+tdda\.referencetest\s+import\s+)(.*)', line)
            if m:
                lines[i] = m.group(1) + m.group(2).rstrip() + ', tag\n'
                tag_imported = True
                break
        if not tag_imported:
            # No tdda.referencetest import found — insert one after last import
            last_import = 0
            for i, line in enumerate(lines):
                if re.match(r'\s*(import |from \S+ import )', line):
                    last_import = i
            lines.insert(
                last_import + 1, 'from tdda.referencetest import tag\n'
            )

    # Build lookup: method/function name -> expected class name (or None)
    targets = {}
    for item in items:
        if len(item) == 2:
            targets[item[1]] = item[0]  # method_name -> class_name
        elif len(item) == 1:
            targets[item[0]] = None  # function_name -> no class

    insertions = []  # list of (line_index, indent_str)
    current_class = None
    for i, line in enumerate(lines):
        stripped = line.lstrip()
        indent = line[: len(line) - len(stripped)]

        if stripped.startswith('class '):
            m = re.match(r'class\s+(\w+)', stripped)
            if m:
                current_class = m.group(1)

        if stripped.startswith('def '):
            m = re.match(r'def\s+(\w+)', stripped)
            if m:
                name = m.group(1)
                if name in targets:
                    expected_class = targets[name]
                    if (
                        expected_class is None
                        or expected_class == current_class
                    ):
                        prev = lines[i - 1].strip() if i > 0 else ''
                        if prev != '@tag':
                            insertions.append((i, indent))

    for idx, indent in reversed(insertions):
        lines.insert(idx, indent + '@tag\n')

    n = len(insertions)
    if n or not tag_imported:
        with open(filepath, 'w') as f:
            f.write(''.join(lines))
        print('Added %s to %s' % (plural(n, '@tag decorator'), filepath))
    else:
        print('No new @tag decorators needed in %s' % filepath)


class TaggedTestLoader(unittest.TestLoader):
    """
    Subclass of ``TestLoader``, which strips out any non-tagged tests.
    """

    def __init__(self, check, printer=None):
        unittest.TestLoader.__init__(self)
        self.check = check
        self.print = printer or print

    def loadTestsFromTestCase(self, *args, **kwargs):
        suite = unittest.TestLoader.loadTestsFromTestCase(
            self, *args, **kwargs
        )
        return self._tagged_tests_only(suite)

    def loadTestsFromModule(self, *args, **kwargs):
        suite = unittest.TestLoader.loadTestsFromModule(self, *args, **kwargs)
        return self._tagged_tests_only(suite)

    def loadTestsFromName(self, *args, **kwargs):
        suite = unittest.TestLoader.loadTestsFromName(self, *args, **kwargs)
        return self._tagged_tests_only(suite)

    def loadTestsFromNames(self, *args, **kwargs):
        suite = unittest.TestLoader.loadTestsFromNames(self, *args, **kwargs)
        return self._tagged_tests_only(suite)

    def _tagged_tests_only(self, suite):
        newsuite = unittest.TestSuite()
        cases = set()
        for test in suite:
            if isinstance(test, unittest.suite.TestSuite):
                test = self._tagged_tests_only(test)
            if self.check and not isinstance(test, unittest.suite.TestSuite):
                cases.add(
                    '%s.%s'
                    % (test.__class__.__module__, test.__class__.__name__)
                )
            else:
                newsuite.addTest(test)
        if self.check:
            for module in cases:
                self.print(module)
        return newsuite

    def getTestCaseNames(self, testCaseClass):
        names = unittest.TestLoader.getTestCaseNames(self, testCaseClass)
        if hasattr(testCaseClass, '_tagged'):
            return names
        else:
            return [
                name
                for name in names
                if hasattr(getattr(testCaseClass, name), '_tagged')
            ]


def main():
    """
    Wrapper around the :py:func:`unittest.main()` entry point.
    """
    ReferenceTestCase.main()
