.nh
.TH "TDDA VERIFY" 1 "January 2026" "3.0" "tdda verify manual"
.SH NAME
\fBtdda verify\fR \- Veriify that constraints are satisfied by data

.SH SYNOPSIS
\fBtdda verify\fR [\fB-h\fR] [\fB-?\fR] [\fB-7\fR] [\fB--no-config\fR]
            [\fB--colour\fR] [\fB--no-colour\fR]
            [\fB-epsilon EPSILON\fR] [\fB-a\fR] [\fB-f\fR]
            [\fB-t {strict,sloppy}\fR] [\fB--verify-required-fields\fR]
            [\fB--verify-allowed-fields\fR] [\fB--no-verify-required-fields\fR]
            [\fB--no-verify-allowed-fields\fR] [\fB--varf\fR] [\fB--no-varf\fR]
            [\fB--pandas\fR] [\fB--polars\fR] [\fB--backend\fR \fIBACKEND\fP]
            \fIINPUT\fP [\fICONSTRAINTS\fP]

.SH POSITIONAL ARGUMENTS
\fIINPUT\fP is one of:
  - a csv file or other flat file (e.g. .csv, .txt, .psv)
  - a data frames in a Parquet files (.parquet)
    e.g. from pandas, polars, R
  - Tables from PostgreSQL databases (e.g. postgres:tablename)
  - Tables from MySQL databases (e.g. mysql:tablename)
  - Tables from SQLite databases (e.g. sqlite:tablename)
  - Standard input, stdin. Use \fB-\fR to read specify this.

.PP
Metadata for flat files can also be specified or inferred.
Use \fBtdda help serial\fR, \fBtdda serial --help\fR, or \fBman tdda-serial\fR for
more information.

.PP
\fICONSTRAINTS\fP, if provided, is a JSON .tdda file containing
constraints.

.PP
If no constraints file is provided, a file with the same path as
the input file, with a .tdda extension will be tried.

.SH DESCRIPTION
The \fBtdda verify\fR command is used to check that data conforms
the the constraints specified. Any constraints not satisfied
by the data are reported, together with summary statistics.

.PP
The \fBtdda verify\fR command does \fInot\fP report which records and
values cause constraints to be violated: the companion command
\fBtdda detect\fR performs this function.

.SH OPTIONS
\fB-h\fR, \fB--help\fR              Show this help message and exit
.br
\fB-?\fR, \fB--?\fR                 Same as \fB-h\fR or \fB--help\fR
.br
\fB-7\fR, \fB--ascii\fR             Report without using special characters
.br
\fB-N\fR, \fB--no-config\fR         Skip loading \fB~/.tdda.toml\fR

.PP
\fB--colour\fR                Use colour in terminal output
.br
\fB--no-colour\fR             Do not not use colour in terminal output

.PP
\fB--epsilon\fR \fIEPSILON\fP       Epsilon fuzziness (tolerance for comparisons)

.PP
\fB-a\fR, \fB--all\fR               Report all fields, even if there are no
.br
                        failures
.br
\fB-f\fR, \fB--fields\fR            Report only fields with failures

.PP
\fB-t\fR, \fB--type_checking\fR {\fIstrict\fP,\fIsloppy\fP}
.br
                        "sloppy" means consider all numeric types
.br
                        equivalent

.PP
\fB--verify-required-fields\fR, \fB--vrf\fR
                        Force verify of required fields
.br
\fB--verify-allowed-fields\fR, \fB--vaf\fR
.br
                        Force verify of allowed fields
.br
\fB--no-verify-required-fields\fR, \fB--no-vrf\fR
.br
                        Force no verication of required fields
.br
\fB--no-verify-allowed-fields\fR, \fB--no-vaf\fR
.br
                        Force no verification of allowed fields
.br
\fB--varf\fR, \fB--vraf\fR          Force verification of allowed and required
.br
                        fields
.br
\fB--no-varf\fR, \fB--no-vraf\fR    Force no verification of allowed and required
.br
                        fields

.PP
\fB--pandas\fR, \fB--pd\fR          Use Pandas as DataFrame engine.
.br
\fB--polars\fR, \fB--pl\fR          Use Polars as DataFrame engine.
.br
\fB--backend\fR, \fB-B\fR \fIBACKEND\fP   Backend choice for Pandas
.br
                        (When dataframe engine is Pandas)
.br
                          \fBn\fR for numpy_nullable *
.br
                          \fBa\fR for pyarrow
.br
                          \fBo\fR for original.

.SH SEE ALSO
tdda-detect(1),
tdda-discover(1),
tdda-serial(1)
