.nh
.TH "TDDA HELP" 1 "May 2026" "3.0" "tdda help manual"
.SH NAME
\fBtdda help\fR — Provides help on \fBtdda\fR and its sub-commands.

.SH SYNOPSIS
\fBtdda help\fR
\fBtdda help\fR \fICOMMAND\fP

.SH POSITIONAL ARGUMENTS
\fICOMMAND\fP can be any of:

.PP
\fBdiscover\fR
.br
\fBverify\fR
.br
\fBdetect\fR

.PP
\fBexamples\fR
.br
\fBgentest\fR

.PP
\fBdiff\fR
.br
\fBserial\fR

.PP
\fBtag\fR
.br
\fBconfig\fR

.PP
\fBhelp\fR
.br
\fBversion\fR
.br
\fBtest\fR
.br
\fBinstallman\fR

.SH DESCRIPTION
Shows help on a tdda subcommand or topic.

.PP
Taking inspiration from \fBgit\fR, if the man pages are installed
(see \fBtdda installman\fR), help on main commands can also be obtained with

.PP
\fBman tdda-COMMAND\fR

.PP
For example:

.PP
\fBman tdda-discover\fR

.PP
Help can also be obtained on each command with \fB--help\fR, \fB-h\fR or \fB-?\fR, e.g.

.PP
\fBtdda discover --help\fR

.SH EXAMPLES
\fBtdda help\fR               Shows this help

.PP
\fBtdda help gentest\fR       Shows help on gentest

.SH SEE ALSO
\fBtdda-installman(1)\fR
