.nh
.TH "TDDA TEST" 1 "April 2026" "3.0" "tdda test manual"
.SH NAME
\fBtdda test\fR  -- Run the tdda libraries tests

.SH SYNOPSIS
\fBtdda test\fR

.SH DESCRIPTION
Runs tdda's (internal) tests.

.PP
\fBNOTE:\fP It is hard to guarantee that all will pass on all systems
given that dependencies are not tightly pinned. It is not necessarily
a problem if some tests fail, but is a concern if a very large number
fail.

.SH SEE ALSO
tdda(1),
