.nh
.TH "TDDA VERSION" 1 "January 2026" "3.0" "tdda config manual"
.SH NAME
\fBtdda config\fR \- Shows config settings

.SH SYNOPSIS
\fBtdda config\fR - Shows current config settings
\fBtdda config --current\fR - Shows current config settings
\fBtdda config --default\fR - Shows default config settings
\fBtdda config --file\fR - Shows config file location and contents.

.SH DESCRIPTION
Shows configuration information. Use

.PP
\fB-c\fR, \fB--current\fR or \fBcurrent\fR for the default configuration
\fB-d\fR, \fB--default\fR or \fBdefault\fR for the default configuration
\fB-f\fR, \fB--file\fR or \fBfile\fR for the configuration file location and contents.

.PP
With no argument, it shows the current configuration.

.SH EXAMPLES
\fBtdda config\fR
\fBtdda config -c\fR
\fBtdda config -d\fR
\fBtdda config -f\fR
