.nh
.TH "TDDA EXAMPLES" 1 "May 2026" "3.0" "tdda examples manual"
.SH NAME
\fBtdda examples\fR — Creates example data for TDDA

.SH SYNOPSIS
\fBtdda examples\fR [OUTDIR]
.br
\fBtdda examples\fR [\fIMODULE...\fP] [OUTDIR]
.br
\fBtdda examples\fR \fBall\fR [OUTDIR]

.SH POSITIONAL ARGUMENTS
\fIMODULE\fP can be any of:
  - \fBreferencetest\fR
  - \fBconstraints\fR
  - \fBrexpy\fR
  - \fBgentest\fR
  - \fBbook\fR

.PP
If not specified, all the first four will be created, without
requiring internet access.

.PP
\fIOUTDIR\fP is an optional directory in which to write the example
directories; by default this will be the current working directory (.).

.PP
If \fBall\fR is specified, or \fBbook\fR is included,
the \fBtdda-book-examples\fR will be downloaded from GitHub, which
does require internet access.

.SH DESCRIPTION
Write out example code and data for all examples, by default,
or for a particular module if specified.

.PP
If no module is specified, examples for all four are written out.

.PP
Examples are created in subdirectories of \fIOUTDIR\fP (default: the current directory \fB\&.\fR).

.SH EXAMPLES
1) \fBtdda examples\fR
.br
   Creates the referencetest, constraints, rexpy, and gentest
   examples in \fB\&.\fR

.PP
2) \fBtdda examples gentest\fR
.br
   Creates \fBexamples_gentest\fR in \fB\&.\fR

.PP
3) \fBtdda examples gentest book\fR
.br
   Creates gentest and book examples in \fB\&.\fR

.PP
4) \fBtdda examples all\fR
.br
   Creates all the examples, four from local files and the book
   examples from GitHub in \fB\&.\fR
