.nh
.TH TDDA 1 "May 2026" "3.0" "tdda manual"
.SH NAME
\fBtdda\fR \- test-driven data analysis

.SH SYNOPSIS
\fBtdda discover\fR      Generate constraints for data validation
.br
\fBtdda verify\fR        Verify (validate) data against constraints
.br
\fBtdda detect\fR        Detect data that fails constraints

.PP
\fBtdda examples\fR      Copy the tdda example data and code
.br
\fBtdda gentest\fR       Auto-generate Python tests for code in any language

.PP
\fBtdda diff\fR          Find difference in datasets in parquet or CSV files
.br
\fBtdda serial\fR        Convert or infer flat-file metadata in tdda.serial,
.br
                   CSVW, or Frictionless formats
.br
\fBtdda tag\fR           Tag tests that failed in the last reference test run
.br
\fBtdda config\fR        Show TDDA configuration

.PP
\fBtdda version\fR       Print the TDDA version number
.br
\fBtdda help\fR          Print this help
.br
\fBtdda help COMMAND\fR  Print help on COMMAND (e.g. discover, verify)

.PP
\fBtdda test\fR          Run the tdda library's self-tests.

.SH OPTIONS
\fB-v\fR, \fB--version\fR       Print version number (same as tdda version)
.br
\fB-h\fR, \fB-?\fR, \fB--help\fR      Print this help

.SH SEE ALSO
\fBrexpy(1)\fR

.PP
TDDA Book
\[la]https://book.tdda.info\[ra]
