"""
Rexpy regex quality measures

Tools for scoring how well a regex (or set of regexes) generated by
rexpy fits a population of "true positive" strings, in terms of
regex length, false negative rate and false positive rate.
"""

import math

from collections import namedtuple

from tdda.rexpy.relib import re
from tdda.rexpy.rexutils import PRNGState, Repeat, repeat_cardinality
from tdda.rexpy.xerpy import Xerpy

DEFAULT_MAX_PLUS = 5
DEFAULT_N_SAMPLES = 100_000

#: The canonical (alphabet-independent) character sets matched by
#: `\\d`, `\\w` and `\\s`. `\\D`, `\\W` and `\\S` are their
#: complements within whatever alphabet is in use.
DIGIT_CHARS = '0123456789'
WORD_CHARS = (
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    'abcdefghijklmnopqrstuvwxyz'
    '0123456789_'
)
WHITESPACE_CHARS = ' \t\n\r\f\v'

CANONICAL_CLASSES = {
    'd': DIGIT_CHARS,
    'w': WORD_CHARS,
    's': WHITESPACE_CHARS,
}

CLASS_ESCAPES = 'dDwWsS'
LITERAL_ESCAPES = r'.^$*+?{}[]()|\-'


class Alphabets:
    """
    Named, reusable alphabets for `count_strings`, each a
    bracket-expression string. Add further named alphabets here as
    they're needed.
    """

    #: All 128 ASCII code points, `chr(0)` to `chr(127)`.
    ASCII = '[\x00-\x7f]'


class ResolvedAlphabet(namedtuple('ResolvedAlphabet', 'pattern size')):
    """
    An alphabet resolved from whatever form it was given in (see
    `_resolve_alphabet`) to a compiled `pattern` (`.fullmatch`
    tests membership) and its `size` -- computed arithmetically
    from ranges, without enumerating characters.
    """


class CountRange(namedtuple('CountRange', 'lower upper')):
    """
    A `(lower, upper)` bound on the number of strings admitted by
    a regex that may contain alternation. `lower == upper` when
    the count is exact (no alternation).
    """


def count_strings(pattern, max_plus=DEFAULT_MAX_PLUS, alphabet=None):
    """Count the strings admitted by an anchored regex, which may
    contain top-level alternation, e.g. the `^(R1|R2|...)$` form
    produced by `combine_patterns`.

    Exact counting across alternation in general would require
    knowing how much the branches overlap, which isn't attempted
    beyond one tractable, common case: if every branch is either a
    fixed literal string, or there's exactly one non-literal branch
    and none of the literals match it, the branches are provably
    disjoint and the count is exact. Otherwise, `upper` is the sum of
    the branches' counts (as if they were completely disjoint) and
    `lower` is the max of the branches' counts (as if every branch's
    matches were a subset of the largest one); the true count lies
    somewhere in `[lower, upper]`.

    Args:
        pattern (str): an anchored regex, optionally containing one
            or more (possibly nested) levels of alternation.
        max_plus (int): see `_count_sequence`.
        alphabet (str): see `_count_sequence`.

    Returns:
        int: the count, when it's exact -- always true when
        `pattern` has no alternation, and also whenever `lower`
        and `upper` happen to coincide anyway.
        CountRange: `(lower, upper)` bound otherwise.
    """
    branches = _split_alternation(pattern)
    if len(branches) == 1:
        return _count_sequence(branches[0], max_plus, alphabet)

    literal_values = {}
    non_literal_branches = []
    for b in branches:
        value = _literal_branch_value(b, max_plus)
        if value is None:
            non_literal_branches.append(b)
        else:
            literal_values[b] = value

    if not non_literal_branches:
        # All branches are fixed strings -- distinct literals are
        # always pairwise disjoint, so this is exact.
        return len(set(literal_values.values()))

    if len(non_literal_branches) == 1:
        non_literal = non_literal_branches[0]
        distinct_values = set(literal_values.values())
        if not any(re.fullmatch(non_literal, v) for v in distinct_values):
            # None of the literals overlap the one non-literal
            # branch, so the branches are provably disjoint: exact
            # count is the literal count plus however precisely the
            # non-literal branch's own count is known (int or, if it
            # still has unresolved internal overlap, a CountRange).
            offset = len(distinct_values)
            inner = _as_range(
                count_strings(non_literal, max_plus, alphabet)
            )
            lower = offset + inner.lower
            upper = offset + inner.upper
            return lower if lower == upper else CountRange(lower, upper)

    ranges = [
        _as_range(count_strings(b, max_plus, alphabet)) for b in branches
    ]
    lower = max(r.lower for r in ranges)
    upper = sum(r.upper for r in ranges)
    return lower if lower == upper else CountRange(lower, upper)


def _as_range(n_or_range):
    """Normalize an `int` or `CountRange` to a `CountRange`.

    Args:
        n_or_range (int or CountRange): a count or range to
            normalize.

    Returns:
        CountRange: `n_or_range` unchanged if already a
        `CountRange`, otherwise `(n_or_range, n_or_range)`.
    """
    if isinstance(n_or_range, CountRange):
        return n_or_range
    return CountRange(n_or_range, n_or_range)


def _literal_branch_value(branch, max_plus):
    """Return the fixed string an alternation branch denotes, if it
    is a plain literal (a sequence of unrepeated literal characters,
    no character classes/escapes/groups/quantifiers) -- or `None` if
    it isn't.

    Deliberately conservative: a branch such as `'^[A]$'` has
    cardinality 1 but is *not* treated as literal here, since two
    differently-written singleton branches could coincidentally admit
    the same one string, which would break the disjointness
    reasoning in `count_strings`.

    Args:
        branch (str): an anchored alternation branch, e.g. `'^AB$'`.
        max_plus (int): see `_count_sequence`.

    Returns:
        str: the fixed string `branch` denotes, if it's a plain
        literal.
        None: if it isn't.
    """
    try:
        _validate_pattern(branch)
    except ValueError:
        return None
    atoms = _parse_pattern(branch, max_plus)
    if all(
        kind == 'literal' and repeat == Repeat(1, 1)
        for kind, value, repeat in atoms
    ):
        return ''.join(value for kind, value, repeat in atoms)
    return None


def _count_sequence(pattern, max_plus=DEFAULT_MAX_PLUS, alphabet=None):
    """Count the number of strings admitted by an anchored rexpy
    regex with no top-level `|`, within a given alphabet. May
    contain unquantified `(...)` groups, each of which may itself
    contain alternation -- handled by recursing into `count_strings`
    for each one, so nested/embedded alternation composes depth-first
    through ordinary function recursion.

    The count only makes sense relative to an alphabet: `.` is
    taken to mean "any character in `alphabet`", and `\\D`, `\\W`
    and `\\S` are taken to mean "any character in `alphabet` that
    isn't a digit/word-character/whitespace character" (see
    `CANONICAL_CLASSES`). `\\d`, `\\w` and `\\s` themselves have
    fixed, alphabet-independent sizes (10, 63 and 6).

    Assumes `pattern` uses standard Python-`re`-compatible
    character-class syntax, as produced by rexpy's default
    (`None`/`'perl'`), `'portable'` or `'grep'` output dialects.
    Patterns from the `'posix'` (`[[:digit:]]`) or `'java'`
    (`\\p{Digit}`) dialects are not supported, since their character
    classes aren't standard regex syntax.

    Args:
        pattern (str): an anchored regex with no top-level
            alternation, e.g. `'^[A-Z]{2}\\d{4}$'` or
            `'^A(B|C)D$'`.
        max_plus (int): cap used for unbounded quantifiers. A
            trailing `+` is expanded as if it were `{1,max_plus}`
            and a trailing `*` as if it were `{0,max_plus}`.
        alphabet (str): the universe of characters this pattern is
            evaluated against -- a bracket-expression string (e.g.
            `'[A-Za-z0-9]'`), a plain string of characters (treated
            as that literal set), or `None` for `Alphabets.ASCII`.

    Returns:
        int: the count, when it's exact.
        CountRange: `(lower, upper)` bound, if any group's own count
        (see `count_strings`) is itself inexact.

    Raises:
        ValueError: if the pattern is not anchored, contains a
            top-level `|` or a quantified group, uses an unsupported
            escape, or explicitly references a character that isn't
            in `alphabet` (e.g. a literal character, or a member or
            range endpoint of a bracket expression).
    """
    resolved_alphabet = _resolve_alphabet(alphabet)
    _validate_pattern(pattern)
    total = CountRange(1, 1)
    for kind, value, repeat in _parse_pattern(pattern, max_plus):
        if kind == 'group':
            factor = _as_range(
                count_strings('^%s$' % value, max_plus, alphabet)
            )
        else:
            card = _atom_size(kind, value, resolved_alphabet, pattern)
            factor = _as_range(repeat_cardinality(card, repeat, max_plus))
        total = CountRange(
            total.lower * factor.lower, total.upper * factor.upper
        )
    return total.lower if total.lower == total.upper else total


def _split_alternation(pattern):
    """Split an anchored pattern into its top-level alternatives
    (as produced by `combine_patterns`), each re-anchored with
    `^...$`. Returns `[pattern]` unchanged if `pattern` has no
    top-level alternation.

    Args:
        pattern (str): an anchored regex, as produced by
            `combine_patterns`.

    Returns:
        list of str: `pattern`'s top-level alternatives, each
        re-anchored with `^...$` -- or `[pattern]` unchanged if it
        has no top-level alternation.

    Raises:
        ValueError: if `pattern` is not anchored with `^...$`.
    """
    if not (pattern.startswith('^') and pattern.endswith('$')):
        raise ValueError(
            f'count_strings requires an anchored pattern (^...$): '
            f'{pattern!r}'
        )
    body = pattern[1:-1]
    if body.startswith('(') and _matching_paren(body, 0) == len(body) - 1:
        body = body[1:-1]
    parts = _split_top_level(body, '|')
    if len(parts) == 1:
        return [pattern]
    return ['^%s$' % p for p in parts]


def _matching_paren(s, i):
    """Return the index of the `)` matching the `(` at `s[i]`,
    treating bracket expressions and escapes as opaque units.

    Args:
        s (str): the string to scan.
        i (int): index of the `(` to match.

    Returns:
        int: the index of the matching `)`.
    """
    depth = 0
    j, n = i, len(s)
    while j < n:
        c = s[j]
        if c == '\\':
            j += 2
        elif c == '[':
            j = _charclass_end(s, j, s)
        elif c == '(':
            depth += 1
            j += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return j
            j += 1
        else:
            j += 1
    raise ValueError(f"unterminated '(' in pattern: {s!r}")


def _split_top_level(s, sep):
    """Split `s` on `sep`, ignoring any occurrence nested inside a
    bracket expression, a parenthesised group, or an escape.

    Args:
        s (str): the string to split.
        sep (str): the single-character separator to split on.

    Returns:
        list of str: the parts of `s`, split on top-level `sep`.
    """
    parts = []
    depth = 0
    start = 0
    i, n = 0, len(s)
    while i < n:
        c = s[i]
        if c == '\\':
            i += 2
        elif c == '[':
            i = _charclass_end(s, i, s)
        elif c == '(':
            depth += 1
            i += 1
        elif c == ')':
            depth -= 1
            i += 1
        elif c == sep and depth == 0:
            parts.append(s[start:i])
            i += 1
            start = i
        else:
            i += 1
    parts.append(s[start:])
    return parts


def _validate_pattern(pattern):
    """Check that `pattern` is a pattern `_count_sequence` can
    handle: a valid, anchored regex using only known escapes, with no
    top-level `|` and no *quantified* groups. Unquantified groups
    (which may themselves contain alternation, handled recursively by
    `count_strings`) are fine -- this pre-check only skips over them
    opaquely, the same way it skips over bracket expressions.

    Args:
        pattern (str): the candidate regex to validate.

    Raises:
        ValueError: if the pattern is not supported.
    """
    try:
        re.compile(pattern)
    except re.error as e:
        raise ValueError(f'not a valid regex: {pattern!r} ({e})')
    if not (pattern.startswith('^') and pattern.endswith('$')):
        raise ValueError(
            f'_count_sequence requires an anchored pattern '
            f'(^...$): {pattern!r}'
        )
    body = pattern[1:-1]
    i, n = 0, len(body)
    while i < n:
        c = body[i]
        if c == '\\':
            if i + 1 >= n:
                raise ValueError(
                    f'trailing backslash in pattern: {pattern!r}'
                )
            e = body[i + 1]
            if e not in CLASS_ESCAPES and e not in LITERAL_ESCAPES:
                raise ValueError(
                    f'unsupported escape \\{e} in pattern: {pattern!r}'
                )
            i += 2
        elif c == '[':
            i = _charclass_end(body, i, pattern)
        elif c == '(':
            j = _matching_paren(body, i)
            if j + 1 < n and body[j + 1] in '?*+{':
                raise ValueError(
                    '_count_sequence does not support a quantifier '
                    f'on a group: {pattern!r}'
                )
            i = j + 1
        elif c in ')|':
            raise ValueError(
                '_count_sequence does not support a top-level '
                f"'|' outside a group: {pattern!r}"
            )
        else:
            i += 1


def _charclass_end(body, i, pattern):
    """Return the index just past the closing `]` of the bracket
    expression starting at `body[i]` (which must be `'['`).

    Args:
        body (str): the pattern body containing the bracket
            expression (may differ from `pattern`, e.g. with
            anchors already stripped).
        i (int): index of the opening `[`.
        pattern (str): the full original pattern, used only for
            error messages.

    Returns:
        int: the index just past the closing `]`.
    """
    n = len(body)
    j = i + 1
    if j < n and body[j] == '^':
        j += 1
    if j < n and body[j] == ']':  # literal ']' as first character
        j += 1
    while j < n and body[j] != ']':
        j += 2 if body[j] == '\\' else 1
    if j >= n:
        raise ValueError(f"unterminated '[' in pattern: {pattern!r}")
    return j + 1


def _parse_pattern(pattern, max_plus):
    """Split an anchored regex into a list of `(kind, value, repeat)`
    atoms, where `kind` is `'charclass'` for a character class/
    escape/dot, `'literal'` for a single literal character, or
    `'group'` for an unquantified `(...)` group (`value` is the
    group's inner content, unanchored -- `count_strings` recurses
    into it, since it may itself contain alternation), and `repeat`
    is a `Repeat`.

    Assumes `pattern` has already passed `_validate_pattern` (so any
    group here is unquantified, and there's no top-level `|`).

    Args:
        pattern (str): an anchored regex that has already passed
            `_validate_pattern`.
        max_plus (int): see `_count_sequence`.

    Returns:
        list of tuple: `(kind, value, repeat)` atoms, in order.
    """
    body = pattern[1:-1]
    i = 0
    n = len(body)
    atoms = []
    while i < n:
        c = body[i]
        if c == '\\':
            atom = body[i : i + 2]
            i += 2
            if atom[1] in CLASS_ESCAPES:
                kind, value = 'charclass', atom
            else:
                kind, value = 'literal', atom[1]
        elif c == '[':
            j = _charclass_end(body, i, pattern)
            kind, value = 'charclass', body[i:j]
            i = j
        elif c == '(':
            j = _matching_paren(body, i)
            kind, value = 'group', body[i + 1 : j]
            i = j + 1
        elif c == '.':
            kind, value = 'charclass', '.'
            i += 1
        else:
            kind, value = 'literal', c
            i += 1
        repeat, i = _parse_quantifier(body, i, max_plus)
        atoms.append((kind, value, repeat))
    return atoms


def _parse_quantifier(body, i, max_plus):
    """Parse an optional quantifier starting at `body[i]`.

    Args:
        body (str): the pattern body being scanned.
        i (int): index immediately after the atom whose quantifier
            (if any) starts here.
        max_plus (int): cap used for unbounded quantifiers (`+`,
            `*`, open `{m,}`).

    Returns:
        tuple: `(repeat, i)` -- the atom's `Repeat` range, and the
        index immediately after the quantifier (unchanged if there
        is none).
    """
    n = len(body)
    if i >= n:
        return Repeat(1, 1), i
    c = body[i]
    if c == '?':
        return Repeat(0, 1), i + 1
    if c == '*':
        return Repeat(0, max_plus), i + 1
    if c == '+':
        return Repeat(1, max_plus), i + 1
    if c == '{':
        j = body.index('}', i)
        spec = body[i + 1 : j]
        if ',' in spec:
            m_s, M_s = spec.split(',')
            m = int(m_s) if m_s else 0
            M = int(M_s) if M_s else max(m, max_plus)
        else:
            m = M = int(spec)
        return Repeat(m, M), j + 1
    return Repeat(1, 1), i


def _atom_size(kind, value, alphabet, pattern):
    """Return the number of characters in `alphabet` (a
    `ResolvedAlphabet`) admitted by a single parsed atom (as
    returned by `_parse_pattern`).

    Args:
        kind (str): `'literal'` or `'charclass'`, as returned by
            `_parse_pattern`.
        value (str): the atom's value, as returned by
            `_parse_pattern`.
        alphabet (ResolvedAlphabet): the alphabet to size against.
        pattern (str): the full original pattern, used only for
            error messages.

    Returns:
        int: the number of characters in `alphabet` admitted by
        this atom.

    Raises:
        ValueError: if the atom explicitly references a character
            (a literal, a bracket member/range, or a canonical
            escape member) that isn't in `alphabet`.
    """
    if kind == 'literal':
        _check_subset(value, alphabet, pattern)
        return 1
    if value == '.' or value[0] == '\\':
        code = value if value == '.' else value[1]
        return _escape_size(code, alphabet, pattern)
    negated, members = _charclass_members(value)
    _check_subset(members, alphabet, pattern)
    return alphabet.size - len(members) if negated else len(members)


def _escape_size(code, alphabet, pattern):
    """Return the number of characters in `alphabet` (a
    `ResolvedAlphabet`) matched by `.` (`code='.'`) or a
    `\\d`/`\\D`/`\\w`/`\\W`/`\\s`/`\\S` shorthand escape (`code`
    one of `'dDwWsS'`).

    `.` matches the whole alphabet, except `\\n` (matching Python's
    `re` semantics without `re.DOTALL`, which we never use).

    `\\d` and `\\w` behave like their expanded bracket-class
    equivalents (`[0-9]`, `[A-Za-z0-9_]`): fixed sets (see
    `CANONICAL_CLASSES`) that must be fully present in `alphabet`.

    `\\s` is treated more loosely: whitespace is a soft concept,
    so only whichever of its canonical members are actually in
    `alphabet` count, and it's rejected only if none of them are.

    Upper-case negations are the complement of whatever their
    lower-case counterpart resolved to, within `alphabet`.

    Args:
        code (str): `'.'`, or one of `'dDwWsS'`.
        alphabet (ResolvedAlphabet): the alphabet to size against.
        pattern (str): the full original pattern, used only for
            error messages.

    Returns:
        int: the number of characters in `alphabet` matched.

    Raises:
        ValueError: for `\\d`/`\\w`, if any canonical member is
            missing from `alphabet`; for `\\s`, only if none of
            its canonical members are in `alphabet` at all.
    """
    if code == '.':
        return alphabet.size - (1 if alphabet.pattern.fullmatch('\n') else 0)
    members = CANONICAL_CLASSES[code.lower()]
    if code.lower() == 's':
        present = _intersect_alphabet(members, alphabet, pattern)
    else:
        _check_subset(members, alphabet, pattern)
        present = members
    if code.isupper():
        return alphabet.size - len(present)
    return len(present)


def _intersect_alphabet(members, alphabet, pattern):
    """Return the subset of `members` that `alphabet.pattern`
    matches.

    Args:
        members (iterable of str): the canonical class members to
            intersect (see `CANONICAL_CLASSES`).
        alphabet (ResolvedAlphabet): the alphabet to intersect
            against.
        pattern (str): the full original pattern, used only for
            error messages.

    Returns:
        frozenset: the subset of `members` present in `alphabet`.

    Raises:
        ValueError: if none of `members` is in `alphabet` --
            i.e. the canonical class is entirely disjoint from
            `alphabet`, rather than merely a partial overlap.
    """
    present = frozenset(c for c in members if alphabet.pattern.fullmatch(c))
    if not present:
        raise ValueError(
            f'none of the canonical members {sorted(members)!r} are '
            f'in alphabet: {pattern!r}'
        )
    return present


def _check_subset(chars, alphabet, pattern):
    """Raise if any character in `chars` isn't matched by
    `alphabet.pattern` (a `ResolvedAlphabet`).

    Args:
        chars (iterable of str): the characters that must all be
            in `alphabet`.
        alphabet (ResolvedAlphabet): the alphabet to check
            against.
        pattern (str): the full original pattern, used only for
            error messages.
    """
    extra = sorted(c for c in set(chars) if not alphabet.pattern.fullmatch(c))
    if extra:
        raise ValueError(
            f'pattern uses characters outside alphabet {extra!r}: '
            f'{pattern!r}'
        )


def _resolve_alphabet(alphabet):
    """Resolve `alphabet` (`None`, a bracket-expression string, or
    a plain string of characters) into a `ResolvedAlphabet`.

    Args:
        alphabet (str or None): a bracket-expression string (e.g.
            `'[A-Za-z0-9]'`), a plain string of characters
            (treated as that literal set), or `None` for
            `Alphabets.ASCII`.

    Returns:
        ResolvedAlphabet

    Raises:
        ValueError: if `alphabet` is a negated character class
            (`'[^...]'`), which has no well-defined size on its
            own.
    """
    if alphabet is None:
        alphabet = Alphabets.ASCII
    spec = _alphabet_spec(alphabet)
    negated, ranges = _charclass_ranges(spec)
    if negated:
        raise ValueError(
            f'alphabet cannot be a negated character class: '
            f'{alphabet!r}'
        )
    size = sum(hi - lo + 1 for lo, hi in _merge_ranges(ranges))
    return ResolvedAlphabet(re.compile(spec), size)


def _alphabet_spec(alphabet):
    """Normalize `alphabet` into a canonical bracket-expression
    string: used as-is if it already is one (starts with `[` and
    spans the whole string), otherwise built from its characters.

    Args:
        alphabet (str): as accepted by `_resolve_alphabet`.

    Returns:
        str: a canonical bracket-expression string.
    """
    if (
        alphabet.startswith('[')
        and _charclass_end(alphabet, 0, alphabet) == len(alphabet)
    ):
        return alphabet
    return '[%s]' % _escape_for_charclass(alphabet)


def _escape_for_charclass(chars):
    """Escape characters that are special inside a bracket
    expression (`]`, `^`, `-`, `\\`), for building one from a
    literal set of characters.

    Args:
        chars (iterable of str): the characters to build a
            bracket expression from.

    Returns:
        str: `chars`, sorted and de-duplicated, with any
        character special inside a bracket expression escaped.
    """
    specials = set('\\]^-')
    return ''.join(
        ('\\' + c if c in specials else c) for c in sorted(set(chars))
    )


def _charclass_members(value):
    """Parse a bracket expression such as `'[a-z0-9_]'` or
    `'[^abc]'` into `(negated, members)`, where `members` is the
    explicit, expanded set of characters listed (individually or
    via ranges) -- the characters the class matches if not
    negated, or the characters it excludes if negated.

    Args:
        value (str): a bracket expression, e.g. `'[a-z0-9_]'` or
            `'[^abc]'`.

    Returns:
        tuple: `(negated, members)` -- `negated` (bool), and
        `members` (frozenset of str), the explicit, expanded set
        of characters listed.
    """
    negated, ranges = _charclass_ranges(value)
    members = set()
    for lo, hi in ranges:
        members.update(chr(cp) for cp in range(lo, hi + 1))
    return negated, frozenset(members)


def _charclass_ranges(value):
    """Parse a bracket expression such as `'[a-z0-9_]'` or
    `'[^abc]'` into `(negated, ranges)`, where `ranges` is a list
    of `(lo, hi)` codepoint tuples -- the range endpoints listed
    (individually or via `x-y` ranges) -- without expanding them
    into individual characters.

    Args:
        value (str): a bracket expression, e.g. `'[a-z0-9_]'` or
            `'[^abc]'`.

    Returns:
        tuple: `(negated, ranges)` -- `negated` (bool), and
        `ranges` (list of `(lo, hi)` codepoint tuples), the range
        endpoints listed, without expanding them into individual
        characters.
    """
    body = value[1:-1]  # strip outer '[' and ']'
    negated = body.startswith('^')
    if negated:
        body = body[1:]
    ranges = []
    i, n = 0, len(body)
    while i < n:
        if body[i] == '\\':
            c, i = body[i + 1], i + 2
        else:
            c, i = body[i], i + 1
        if i < n and body[i] == '-' and i + 1 < n:
            i += 1  # skip '-'
            if body[i] == '\\':
                d, i = body[i + 1], i + 2
            else:
                d, i = body[i], i + 1
            ranges.append((ord(c), ord(d)))
        else:
            ranges.append((ord(c), ord(c)))
    return negated, ranges


def _merge_ranges(ranges):
    """Merge overlapping or adjacent `(lo, hi)` codepoint ranges,
    so that summing their sizes doesn't double-count.

    Args:
        ranges (list of tuple): `(lo, hi)` codepoint ranges.

    Returns:
        list of tuple: the merged, non-overlapping `(lo, hi)`
        ranges.
    """
    merged = []
    for lo, hi in sorted(ranges):
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))
    return merged


def _rate(numerator, denominator):
    """Compute `numerator / denominator` as a rate, treating the
    degenerate cases sensibly rather than raising:

    - `0/0` is `0.0` (no false results occurred, regardless of
      whether there was theoretically room for any).
    - a positive numerator over a zero denominator is
      `float('inf')` (the regex admits things entirely outside
      what the assumed universe accounts for).

    Args:
        numerator (int): the numerator.
        denominator (int): the denominator.

    Returns:
        float: the rate, per the degenerate-case rules above.
    """
    if denominator == 0:
        return 0.0 if numerator == 0 else float('inf')
    return numerator / denominator


def _range_ratio(numerator, denominator):
    """`_rate(numerator, denominator)`, but either side may be a
    `CountRange` instead of a scalar -- paired lower-with-lower,
    upper-with-upper. Collapses to a scalar when the resulting bounds
    coincide, matching `count_strings`'s own convention.

    Args:
        numerator (int, float or CountRange): the numerator.
        denominator (int, float or CountRange): the denominator.

    Returns:
        float or CountRange
    """
    num_lower, num_upper = (
        (numerator.lower, numerator.upper)
        if isinstance(numerator, CountRange) else (numerator, numerator)
    )
    den_lower, den_upper = (
        (denominator.lower, denominator.upper)
        if isinstance(denominator, CountRange) else (denominator, denominator)
    )
    lower = _rate(num_lower, den_lower)
    upper = _rate(num_upper, den_upper)
    return lower if lower == upper else CountRange(lower, upper)


class RexMetrics:
    """
    Quality metrics for a single regex, scored against a set of
    positive examples.

    Args:
        len (int): length of the regex string.
        fp (int or CountRange): false positive count. In
            `ConcreteRexMetric`'s default (cardinality-based) mode:
            strings the regex admits beyond the true positives it
            actually matches -- a `CountRange` if the pattern has
            alternation with genuine overlap uncertainty, an `int`
            otherwise (see `count_strings`). In validator mode (see
            `ConcreteRexMetric.evaluate`): a plain `int` count of
            samples drawn from the candidate pattern that fail the
            validator -- a different statistic, computed without
            `count_strings` at all.
        fn (int): false negative count -- true positives the regex
            fails to match. Always exact (found by directly testing
            the compiled pattern against the real positives), never
            a range, regardless of alternation.
        fpr (float or CountRange): false positive rate, `fp` divided
            by the number of "invalid" strings in the assumed
            universe (`universe - n_positives`) -- the same
            statistic, comparable in scale, in both modes. In the
            default mode this is exact (up to `count_strings`'s own
            bounds). In validator mode there's no real per-string
            enumeration of the universe, so it's derived instead by
            extrapolating the sampled `fgr` up to the candidate
            pattern's own cardinality (via `count_strings`) and
            dividing by `universe - n_positives` -- approximating
            what exhaustive enumeration-and-cross-check against the
            validator would give. A `CountRange` of rates iff the
            underlying cardinality is a `CountRange`. Optional;
            `eq()` only compares it when given (on either side).
        fnr (float): false negative rate (`fn / n_positives`).
            Optional, compared by `eq()` only when given.
        fgr (float or CountRange): false generation rate -- the
            fraction of what the candidate pattern matches/generates
            that isn't a real positive (`fp` over the candidate's own
            matched space, not the universe). In the default mode:
            `fp / cardinality(pattern)`, exact up to the same bounds
            as `fpr`. In validator mode: `fp` divided by the number
            of (deduped) candidate samples drawn from the pattern --
            a sampling estimate of the same ratio. This is the
            statistic validator mode used to (mis)report as `fpr`
            before `fpr` was given its proper, universe-relative
            meaning. Optional; `eq()` only compares it when given.
        universe (int): size of the assumed universe of possible
            strings. Not itself a quality measure (it's context,
            not a property of the regex), so `eq()` never compares
            it directly -- but uses it to derive a default `tol`
            when one isn't given explicitly. `None` in validator
            mode: `self.universe` is still used internally there to
            derive `fpr`, but isn't exposed via this field, since the
            candidate pattern's cardinality (not the full alphabet/
            length universe) is what validator mode actually samples
            over.
    """

    def __init__(
        self, len, fp, fn, fpr=None, fnr=None, fgr=None, universe=None,
    ):
        self.len = len
        self.fp = fp
        self.fn = fn
        self.fpr = fpr
        self.fnr = fnr
        self.fgr = fgr
        self.universe = universe

    def eq(self, other, tol=None):
        """Compare quality against `other`.

        `len`, `fp` and `fn` are always compared exactly (`fp`
        may be an `int` or a `CountRange`; plain `==` already
        does the right thing either way, including correctly
        rejecting a mismatch between the two). `fpr` and `fnr`
        are compared (within `tol`) only if `other` specifies
        them (is not `None`) -- letting `other` be a
        partially-specified expected value. Each is compared as a
        single float, or component-wise if both sides are a
        `CountRange` of rates; a scalar vs. `CountRange` mismatch
        is simply unequal (this is a convenience for readable
        tests, not a general-purpose comparison, so callers are
        expected to know which shape to expect).

        `tol` defaults to the smaller of `1/(10*universe)` over
        whichever of `self`/`other` have a `universe` set, or
        `0.0` (exact comparison) if neither does.

        Args:
            other (RexMetrics): the expected value to compare
                against.
            tol (float): tolerance for `fpr`/`fnr`/`fgr` comparison.
                Defaults to `_default_tol(self, other)` when not
                given.

        Returns:
            bool
        """
        if self.len != other.len or self.fp != other.fp:
            return False
        if self.fn != other.fn:
            return False
        if tol is None:
            tol = _default_tol(self, other)
        for attr in ('fpr', 'fnr', 'fgr'):
            expected = getattr(other, attr)
            if expected is None:
                continue
            actual = getattr(self, attr)
            if not _rates_close(actual, expected, tol):
                return False
        return True


def _rates_close(actual, expected, tol):
    """Compare two rates (each a single `float` or a `CountRange`
    of rates) within `tol`. A scalar/`CountRange` mismatch is
    always unequal.

    Args:
        actual (float or CountRange): the computed rate.
        expected (float or CountRange): the expected rate.
        tol (float): absolute tolerance for the comparison.

    Returns:
        bool
    """
    if isinstance(actual, CountRange) != isinstance(expected, CountRange):
        return False
    if isinstance(actual, CountRange):
        return math.isclose(
            actual.lower, expected.lower, abs_tol=tol
        ) and math.isclose(actual.upper, expected.upper, abs_tol=tol)
    return actual is not None and math.isclose(
        actual, expected, abs_tol=tol
    )


def _default_tol(a, b):
    """Derive a default tolerance for `RexMetrics.eq()` from
    whichever of `a`/`b` have a `universe` set: the smaller of
    `1/(10*universe)` over those that do, or `0.0` if neither does.

    Args:
        a (RexMetrics): one side of the comparison.
        b (RexMetrics): the other side.

    Returns:
        float
    """
    candidates = [
        1 / (10 * m.universe)
        for m in (a, b)
        if m.universe is not None and m.universe > 0
    ]
    return min(candidates) if candidates else 0.0


class ConcreteRexMetric:
    """
    A reusable scorer bound to a fixed set of positive examples,
    alphabet and length range. Call `evaluate(pattern)` once per
    candidate regex to score it against them.

    Args:
        all_positives (list/tuple, callable, or str): the positive
            examples to score candidate regexes against. A list or
            tuple is used as-is, including any duplicates -- never
            deduped, since it's the caller's explicit data. A
            zero-argument callable is called `n_positives` times to
            materialize a sample (e.g. `lambda: xerpy(regex)`),
            then deduped (duplicates there are an artifact of
            sampling with replacement, not meaningful data). A str
            is treated as a regex and handed to `Xerpy` internally,
            then materialized the same way as a callable.
        alphabet (str): see `_resolve_alphabet`.
        min_length (int): minimum string length in the assumed
            universe. Defaults to the shortest of `all_positives`.
        max_length (int): maximum string length in the assumed
            universe. Defaults to the longest of `all_positives`.
        n_positives (int): number of times to call `all_positives`
            when it's a callable or str, before deduping. Ignored
            when it's a list/tuple. Defaults to `DEFAULT_N_SAMPLES`
            (100,000).
        seed (int): PRNG seed used while materializing a callable/
            str `all_positives` (see `PRNGState`), and reused by
            `evaluate()` for candidate-sampling when `validator` is
            set; restored afterwards regardless. `None` leaves the
            caller's PRNG state untouched (and samples
            unreproducible).
        validator (callable): an optional `str -> bool` oracle used
            by `evaluate()` to compute `fp`/`fpr` by sampling from
            the *candidate* pattern and checking each sample against
            it, instead of the cardinality-based calculation (see
            `evaluate()`). If `all_positives` is a regex string and
            `validator` isn't given explicitly, one is derived
            automatically (`lambda s: bool(re.fullmatch(spec, s))`).
            Needed because the cardinality-based `fp` calculation
            assumes `all_positives` is the *complete* population of
            true positives -- true for a real, near-exhaustive
            dataset, but not for a sample drawn from a generator,
            where "matched by the candidate but not in this sample"
            conflates real false positives with true positives that
            simply weren't drawn.
        weighted (bool): passed through to every `Xerpy` used
            internally (both for materializing `all_positives` and,
            in `evaluate()`, for candidate-sampling) -- see
            `Xerpy.__init__`. Defaults to `False` (uniform
            alternation-branch choice), matching `Xerpy`'s own
            default.
    """

    def __init__(
        self, all_positives, alphabet=None, min_length=None,
        max_length=None, n_positives=DEFAULT_N_SAMPLES, seed=None,
        validator=None, weighted=False,
    ):
        self.seed = seed
        self.weighted = weighted
        spec = all_positives if isinstance(all_positives, str) else None
        if validator is None and spec is not None:
            compiled_spec = re.compile(spec)
            validator = lambda s: bool(compiled_spec.fullmatch(s))
        self.validator = validator
        if isinstance(all_positives, str):
            all_positives = Xerpy(all_positives, weighted=weighted).generate
        if callable(all_positives):
            generate = all_positives
            prng_state = PRNGState(seed)
            try:
                all_positives = list(
                    {generate() for _ in range(n_positives)}
                )
            finally:
                prng_state.restore()
        self.all_positives = all_positives
        self.alphabet = alphabet
        self.n_positives = len(all_positives)
        lengths = [len(s) for s in all_positives]
        self.min_length = min(lengths) if min_length is None else min_length
        self.max_length = max(lengths) if max_length is None else max_length
        resolved = _resolve_alphabet(alphabet)
        self.universe = sum(
            resolved.size**k
            for k in range(self.min_length, self.max_length + 1)
        )

    def evaluate(
        self, pattern, max_plus=DEFAULT_MAX_PLUS,
        n_candidates=DEFAULT_N_SAMPLES,
    ):
        """Score `pattern` against `self.all_positives`.

        `pattern` may contain alternation: `count_strings` returns
        an `int` when the cardinality is exact, or a `CountRange`
        when alternation leaves genuine overlap uncertainty, and
        `fp`/`fpr`/`fgr` follow suit.

        `max_plus` is passed through to `count_strings`, to size
        unbounded quantifiers (`+`, `*`, open `{m,}`); it defaults
        to `DEFAULT_MAX_PLUS` (5), which may not reach `self`'s
        actual `max_length` for patterns using them.

        If `self.validator` is set, `fp`/`fgr` are computed
        differently: `n_candidates` strings are sampled from
        `pattern` itself (via `Xerpy`, seeded/restored the same way
        as `all_positives`), deduped, and checked against
        `self.validator` -- `fp` is how many fail it, `fgr` is that
        count over the deduped sample size (a sampling estimate of
        the fraction of `pattern`'s own output that isn't a real
        positive). `fpr` is then derived by extrapolating `fgr` up to
        `pattern`'s cardinality (via `count_strings`, run in this
        mode too, unlike before) and dividing by `self.universe -
        self.n_positives` -- approximating what exhaustively
        enumerating `pattern`'s matches and cross-checking each
        against the validator would give, the same statistic the
        default mode computes.

        Args:
            pattern (str): the candidate regex to score.
            max_plus (int): see `count_strings`.
            n_candidates (int): number of samples to draw from
                `pattern` when `self.validator` is set. Unused
                otherwise.

        Returns:
            RexMetrics
        """
        compiled = re.compile(pattern)
        fn = sum(
            1 for s in self.all_positives if not compiled.fullmatch(s)
        )
        fnr = _rate(fn, self.n_positives)
        if self.validator is not None:
            generate = Xerpy(pattern, weighted=self.weighted).generate
            prng_state = PRNGState(self.seed)
            try:
                candidates = list(
                    {generate() for _ in range(n_candidates)}
                )
            finally:
                prng_state.restore()
            fp = sum(1 for s in candidates if not self.validator(s))
            fgr = _rate(fp, len(candidates))
            cardinality = count_strings(
                pattern, max_plus=max_plus, alphabet=self.alphabet
            )
            fp_denominator = self.universe - self.n_positives
            if isinstance(cardinality, CountRange):
                fp_estimate = CountRange(
                    fgr * cardinality.lower, fgr * cardinality.upper
                )
            else:
                fp_estimate = fgr * cardinality
            # Same clamping rationale as the default mode below: an
            # extrapolated estimate can in principle land outside
            # [0, fp_denominator] (sampling noise, or count_strings's
            # own over/under-estimation), which isn't a legitimate
            # fpr; clamp before deriving the rate.
            if isinstance(fp_estimate, CountRange):
                fp_estimate = CountRange(
                    max(fp_estimate.lower, 0), max(fp_estimate.upper, 0)
                )
                if fp_denominator > 0:
                    fp_estimate = CountRange(
                        min(fp_estimate.lower, fp_denominator),
                        min(fp_estimate.upper, fp_denominator),
                    )
            else:
                fp_estimate = max(fp_estimate, 0)
                if fp_denominator > 0:
                    fp_estimate = min(fp_estimate, fp_denominator)
            fpr = _range_ratio(fp_estimate, fp_denominator)
            return RexMetrics(
                len=len(pattern), fp=fp, fn=fn, fpr=fpr, fnr=fnr,
                fgr=fgr, universe=None,
            )
        cardinality = count_strings(
            pattern, max_plus=max_plus, alphabet=self.alphabet
        )
        n_true_matched = self.n_positives - fn
        fp_denominator = self.universe - self.n_positives
        # fp can never legitimately exceed fp_denominator (a false
        # positive is, by definition, one of the actual negatives,
        # so fpr = fp / (fp + TN) <= 1 always). count_strings's
        # approximations (unbounded quantifiers reaching past
        # max_length, or alternation's sum-as-upper-bound when
        # branches overlap) can overshoot that bound; clamping
        # enforces the invariant rather than reporting fpr > 1.
        # When fp_denominator is 0 (no room for any false
        # positives at all), that's a special case handled by
        # _rate itself (0/0 -> 0.0, positive/0 -> inf) -- clamping
        # doesn't apply there.
        if isinstance(cardinality, CountRange):
            fp = CountRange(
                cardinality.lower - n_true_matched,
                cardinality.upper - n_true_matched,
            )
            # fp can also never legitimately be negative: the
            # max()-of-branches heuristic behind cardinality.lower
            # can undershoot the true cardinality (e.g. many
            # disjoint literal branches), making the subtraction
            # dip below zero even though the real fp cannot.
            fp = CountRange(max(fp.lower, 0), max(fp.upper, 0))
            if fp_denominator > 0:
                fp = CountRange(
                    min(fp.lower, fp_denominator),
                    min(fp.upper, fp_denominator),
                )
            # Collapse to a scalar when the bounds coincide, e.g.
            # after clamping -- matching count_strings's own
            # lower/upper-collapse convention for cardinality.
            if fp.lower == fp.upper:
                fp = fp.lower
                fpr = _rate(fp, fp_denominator)
            else:
                fpr = CountRange(
                    _rate(fp.lower, fp_denominator),
                    _rate(fp.upper, fp_denominator),
                )
        else:
            fp = cardinality - n_true_matched
            # Unlike the CountRange branch, this can never
            # legitimately be negative: cardinality is exact here
            # (that's why it's a plain int, not a CountRange), and
            # n_true_matched counts distinct positives (all_positives
            # has no duplicates), so it's a subset-count of the
            # cardinality-count set and can't exceed it.
            assert fp >= 0
            if fp_denominator > 0:
                fp = min(fp, fp_denominator)
            fpr = _rate(fp, fp_denominator)
        # fgr: what fraction of what `pattern` itself matches isn't
        # a real positive -- unlike fpr (relative to the universe),
        # this is relative to `pattern`'s own cardinality. Uses the
        # (clamped) fp computed above and the original, unclamped
        # cardinality.
        fgr = _range_ratio(fp, cardinality)
        return RexMetrics(
            len=len(pattern), fp=fp, fn=fn, fpr=fpr, fnr=fnr, fgr=fgr,
            universe=self.universe,
        )
