"""
Rexpy regex quality measures

Tools for scoring how well a regex (or set of regexes) generated by
rexpy fits a population of "true positive" strings, in terms of
regex length, false negative rate and false positive rate.
"""

from collections import namedtuple

from tdda.rexpy.relib import re

DEFAULT_MAX_PLUS = 5

#: The canonical (alphabet-independent) character sets matched by
#: `\\d`, `\\w` and `\\s`. `\\D`, `\\W` and `\\S` are their
#: complements within whatever alphabet is in use.
DIGIT_CHARS = '0123456789'
WORD_CHARS = (
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    'abcdefghijklmnopqrstuvwxyz'
    '0123456789_'
)
WHITESPACE_CHARS = ' \t\n\r\f\v'

CANONICAL_CLASSES = {
    'd': DIGIT_CHARS,
    'w': WORD_CHARS,
    's': WHITESPACE_CHARS,
}

CLASS_ESCAPES = 'dDwWsS'
LITERAL_ESCAPES = r'.^$*+?{}[]()|\-'


class Alphabets:
    """
    Named, reusable alphabets for `count_strings`. Add further
    named alphabets here as they're needed.
    """

    #: All 128 ASCII code points, `chr(0)` to `chr(127)`.
    ASCII = ''.join(chr(c) for c in range(128))


class Repeat(namedtuple('Repeat', 'min max')):
    """
    A repeat range for a single regex atom (e.g. `{2,4}` gives
    `Repeat(min=2, max=4)`).
    """


def count_strings(pattern, max_plus=DEFAULT_MAX_PLUS, alphabet=None):
    """Count the number of strings admitted by an anchored,
    alternation-free rexpy regex, within a given alphabet.

    The count only makes sense relative to an alphabet: `.` is
    taken to mean "any character in `alphabet`", and `\\D`, `\\W`
    and `\\S` are taken to mean "any character in `alphabet` that
    isn't a digit/word-character/whitespace character" (see
    `CANONICAL_CLASSES`). `\\d`, `\\w` and `\\s` themselves have
    fixed, alphabet-independent sizes (10, 63 and 6).

    Assumes `pattern` uses standard Python-`re`-compatible
    character-class syntax, as produced by rexpy's default
    (`None`/`'perl'`), `'portable'` or `'grep'` output dialects.
    Patterns from the `'posix'` (`[[:digit:]]`) or `'java'`
    (`\\p{Digit}`) dialects are not supported, since their character
    classes aren't standard regex syntax.

    Args:
        pattern (str): an anchored regex with no top-level
            alternation, e.g. `'^[A-Z]{2}\\d{4}$'`.
        max_plus (int): cap used for unbounded quantifiers. A
            trailing `+` is expanded as if it were `{1,max_plus}`
            and a trailing `*` as if it were `{0,max_plus}`.
        alphabet (str): the universe of characters this pattern is
            evaluated against. Defaults to `Alphabets.ASCII`.

    Returns:
        int: number of distinct strings the pattern can match.

    Raises:
        ValueError: if the pattern is not anchored, contains
            alternation or groups, uses an unsupported escape, or
            explicitly references a character that isn't in
            `alphabet` (e.g. a literal character, or a member or
            range endpoint of a bracket expression).
    """
    alphabet = Alphabets.ASCII if alphabet is None else alphabet
    _validate_pattern(pattern)
    total = 1
    for kind, value, repeat in _parse_pattern(pattern, max_plus):
        card = _atom_size(kind, value, alphabet, pattern)
        total *= sum(card**k for k in range(repeat.min, repeat.max + 1))
    return total


def _validate_pattern(pattern):
    """Check that `pattern` is a pattern `count_strings` can
    handle: a valid regex that is anchored, alternation-free, and
    uses only known escapes.

    Raises:
        ValueError: if the pattern is not supported.
    """
    try:
        re.compile(pattern)
    except re.error as e:
        raise ValueError(f'not a valid regex: {pattern!r} ({e})')
    if not (pattern.startswith('^') and pattern.endswith('$')):
        raise ValueError(
            f'count_strings requires an anchored pattern (^...$): '
            f'{pattern!r}'
        )
    body = pattern[1:-1]
    i, n = 0, len(body)
    while i < n:
        c = body[i]
        if c == '\\':
            if i + 1 >= n:
                raise ValueError(
                    f'trailing backslash in pattern: {pattern!r}'
                )
            e = body[i + 1]
            if e not in CLASS_ESCAPES and e not in LITERAL_ESCAPES:
                raise ValueError(
                    f'unsupported escape \\{e} in pattern: {pattern!r}'
                )
            i += 2
        elif c == '[':
            i = _charclass_end(body, i, pattern)
        elif c in '()|':
            raise ValueError(
                'count_strings does not support alternation or '
                f'groups: {pattern!r}'
            )
        else:
            i += 1


def _charclass_end(body, i, pattern):
    """Return the index just past the closing `]` of the bracket
    expression starting at `body[i]` (which must be `'['`).
    """
    n = len(body)
    j = i + 1
    if j < n and body[j] == '^':
        j += 1
    if j < n and body[j] == ']':  # literal ']' as first character
        j += 1
    while j < n and body[j] != ']':
        j += 2 if body[j] == '\\' else 1
    if j >= n:
        raise ValueError(f"unterminated '[' in pattern: {pattern!r}")
    return j + 1


def _parse_pattern(pattern, max_plus):
    """Split an anchored, alternation-free regex into a list of
    `(kind, value, repeat)` atoms, where `kind` is `'charclass'`
    for a character class/escape/dot and `'literal'` for a single
    literal character, and `repeat` is a `Repeat`.

    Assumes `pattern` has already passed `_validate_pattern`.
    """
    body = pattern[1:-1]
    i = 0
    n = len(body)
    atoms = []
    while i < n:
        c = body[i]
        if c == '\\':
            atom = body[i : i + 2]
            i += 2
            if atom[1] in CLASS_ESCAPES:
                kind, value = 'charclass', atom
            else:
                kind, value = 'literal', atom[1]
        elif c == '[':
            j = _charclass_end(body, i, pattern)
            kind, value = 'charclass', body[i:j]
            i = j
        elif c == '.':
            kind, value = 'charclass', '.'
            i += 1
        else:
            kind, value = 'literal', c
            i += 1
        repeat, i = _parse_quantifier(body, i, max_plus)
        atoms.append((kind, value, repeat))
    return atoms


def _parse_quantifier(body, i, max_plus):
    """Parse an optional quantifier starting at `body[i]`.

    Returns `(repeat, i)`: the atom's `Repeat` range, and the
    index immediately after the quantifier (unchanged if there is
    none).
    """
    n = len(body)
    if i >= n:
        return Repeat(1, 1), i
    c = body[i]
    if c == '?':
        return Repeat(0, 1), i + 1
    if c == '*':
        return Repeat(0, max_plus), i + 1
    if c == '+':
        return Repeat(1, max_plus), i + 1
    if c == '{':
        j = body.index('}', i)
        spec = body[i + 1 : j]
        if ',' in spec:
            m_s, M_s = spec.split(',')
            m = int(m_s) if m_s else 0
            M = int(M_s) if M_s else max(m, max_plus)
        else:
            m = M = int(spec)
        return Repeat(m, M), j + 1
    return Repeat(1, 1), i


def _atom_size(kind, value, alphabet, pattern):
    """Return the number of characters in `alphabet` admitted by a
    single parsed atom (as returned by `_parse_pattern`).

    Raises:
        ValueError: if the atom explicitly references a character
            (a literal, a bracket member/range, or a canonical
            escape member) that isn't in `alphabet`.
    """
    if kind == 'literal':
        _check_subset(value, alphabet, pattern)
        return 1
    if value == '.' or value[0] == '\\':
        code = value if value == '.' else value[1]
        return _escape_size(code, alphabet, pattern)
    negated, members = _charclass_members(value)
    _check_subset(members, alphabet, pattern)
    return len(alphabet) - len(members) if negated else len(members)


def _escape_size(code, alphabet, pattern):
    """Return the number of characters in `alphabet` matched by
    `.` (`code='.'`) or a `\\d`/`\\D`/`\\w`/`\\W`/`\\s`/`\\S`
    shorthand escape (`code` one of `'dDwWsS'`).

    `.` matches the whole alphabet. `\\d`/`\\w`/`\\s` have fixed,
    alphabet-independent sizes (see `CANONICAL_CLASSES`); their
    upper-case negations are the complement within `alphabet`.

    Raises:
        ValueError: if the escape's canonical members aren't all
            present in `alphabet`.
    """
    if code == '.':
        return len(alphabet)
    members = CANONICAL_CLASSES[code.lower()]
    _check_subset(members, alphabet, pattern)
    if code.isupper():
        return len(alphabet) - len(members)
    return len(members)


def _check_subset(chars, alphabet, pattern):
    """Raise if any character in `chars` is not in `alphabet`."""
    extra = sorted(set(chars) - set(alphabet))
    if extra:
        raise ValueError(
            f'pattern uses characters outside alphabet {extra!r}: '
            f'{pattern!r}'
        )


def _charclass_members(value):
    """Parse a bracket expression such as `'[a-z0-9_]'` or
    `'[^abc]'` into `(negated, members)`, where `members` is the
    explicit set of characters listed (individually or via ranges)
    -- the characters the class matches if not negated, or the
    characters it excludes if negated.
    """
    body = value[1:-1]  # strip outer '[' and ']'
    negated = body.startswith('^')
    if negated:
        body = body[1:]
    members = set()
    i, n = 0, len(body)
    while i < n:
        if body[i] == '\\':
            c, i = body[i + 1], i + 2
        else:
            c, i = body[i], i + 1
        if i < n and body[i] == '-' and i + 1 < n:
            i += 1  # skip '-'
            if body[i] == '\\':
                d, i = body[i + 1], i + 2
            else:
                d, i = body[i], i + 1
            members.update(chr(cp) for cp in range(ord(c), ord(d) + 1))
        else:
            members.add(c)
    return negated, frozenset(members)
