"""
Rexpy regex quality measures

Tools for scoring how well a regex (or set of regexes) generated by
rexpy fits a population of "true positive" strings, in terms of
regex length, false negative rate and false positive rate.
"""

import math

from collections import namedtuple

from tdda.rexpy.relib import re

DEFAULT_MAX_PLUS = 5

#: The canonical (alphabet-independent) character sets matched by
#: `\\d`, `\\w` and `\\s`. `\\D`, `\\W` and `\\S` are their
#: complements within whatever alphabet is in use.
DIGIT_CHARS = '0123456789'
WORD_CHARS = (
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    'abcdefghijklmnopqrstuvwxyz'
    '0123456789_'
)
WHITESPACE_CHARS = ' \t\n\r\f\v'

CANONICAL_CLASSES = {
    'd': DIGIT_CHARS,
    'w': WORD_CHARS,
    's': WHITESPACE_CHARS,
}

CLASS_ESCAPES = 'dDwWsS'
LITERAL_ESCAPES = r'.^$*+?{}[]()|\-'


class Alphabets:
    """
    Named, reusable alphabets for `count_strings`, each a
    bracket-expression string. Add further named alphabets here as
    they're needed.
    """

    #: All 128 ASCII code points, `chr(0)` to `chr(127)`.
    ASCII = '[\x00-\x7f]'


class Repeat(namedtuple('Repeat', 'min max')):
    """
    A repeat range for a single regex atom (e.g. `{2,4}` gives
    `Repeat(min=2, max=4)`).
    """


class ResolvedAlphabet(namedtuple('ResolvedAlphabet', 'pattern size')):
    """
    An alphabet resolved from whatever form it was given in (see
    `_resolve_alphabet`) to a compiled `pattern` (`.fullmatch`
    tests membership) and its `size` -- computed arithmetically
    from ranges, without enumerating characters.
    """


class CountRange(namedtuple('CountRange', 'lower upper')):
    """
    A `(lower, upper)` bound on the number of strings admitted by
    a regex that may contain alternation. `lower == upper` when
    the count is exact (no alternation).
    """


def count_strings(pattern, max_plus=DEFAULT_MAX_PLUS, alphabet=None):
    """Count the strings admitted by an anchored regex, which may
    contain top-level alternation, e.g. the `^(R1|R2|...)$` form
    produced by `combine_patterns`.

    Exact counting across alternation would require knowing how
    much the branches overlap, which isn't attempted: `upper` is
    the sum of the branches' counts (as if they were completely
    disjoint); `lower` is the max of the branches' counts (as if
    every branch's matches were a subset of the largest one). The
    true count lies somewhere in `[lower, upper]`.

    Args:
        pattern (str): an anchored regex, optionally containing one
            or more (possibly nested) levels of alternation.
        max_plus (int): see `count_strings_no_alt`.
        alphabet (str): see `count_strings_no_alt`.

    Returns:
        int: the count, when it's exact -- always true when
        `pattern` has no alternation, and also whenever `lower`
        and `upper` happen to coincide anyway.
        CountRange: `(lower, upper)` bound otherwise.
    """
    branches = _split_alternation(pattern)
    if len(branches) == 1:
        return count_strings_no_alt(branches[0], max_plus, alphabet)
    ranges = [
        _as_range(count_strings(b, max_plus, alphabet)) for b in branches
    ]
    lower = max(r.lower for r in ranges)
    upper = sum(r.upper for r in ranges)
    return lower if lower == upper else CountRange(lower, upper)


def _as_range(n_or_range):
    """Normalize an `int` or `CountRange` to a `CountRange`."""
    if isinstance(n_or_range, CountRange):
        return n_or_range
    return CountRange(n_or_range, n_or_range)


def count_strings_no_alt(pattern, max_plus=DEFAULT_MAX_PLUS, alphabet=None):
    """Count the number of strings admitted by an anchored,
    alternation-free rexpy regex, within a given alphabet.

    The count only makes sense relative to an alphabet: `.` is
    taken to mean "any character in `alphabet`", and `\\D`, `\\W`
    and `\\S` are taken to mean "any character in `alphabet` that
    isn't a digit/word-character/whitespace character" (see
    `CANONICAL_CLASSES`). `\\d`, `\\w` and `\\s` themselves have
    fixed, alphabet-independent sizes (10, 63 and 6).

    Assumes `pattern` uses standard Python-`re`-compatible
    character-class syntax, as produced by rexpy's default
    (`None`/`'perl'`), `'portable'` or `'grep'` output dialects.
    Patterns from the `'posix'` (`[[:digit:]]`) or `'java'`
    (`\\p{Digit}`) dialects are not supported, since their character
    classes aren't standard regex syntax.

    Args:
        pattern (str): an anchored regex with no top-level
            alternation, e.g. `'^[A-Z]{2}\\d{4}$'`.
        max_plus (int): cap used for unbounded quantifiers. A
            trailing `+` is expanded as if it were `{1,max_plus}`
            and a trailing `*` as if it were `{0,max_plus}`.
        alphabet (str): the universe of characters this pattern is
            evaluated against -- a bracket-expression string (e.g.
            `'[A-Za-z0-9]'`), a plain string of characters (treated
            as that literal set), or `None` for `Alphabets.ASCII`.

    Returns:
        int: number of distinct strings the pattern can match.

    Raises:
        ValueError: if the pattern is not anchored, contains
            alternation or groups, uses an unsupported escape, or
            explicitly references a character that isn't in
            `alphabet` (e.g. a literal character, or a member or
            range endpoint of a bracket expression).
    """
    alphabet = _resolve_alphabet(alphabet)
    _validate_pattern(pattern)
    total = 1
    for kind, value, repeat in _parse_pattern(pattern, max_plus):
        card = _atom_size(kind, value, alphabet, pattern)
        total *= sum(card**k for k in range(repeat.min, repeat.max + 1))
    return total


def _split_alternation(pattern):
    """Split an anchored pattern into its top-level alternatives
    (as produced by `combine_patterns`), each re-anchored with
    `^...$`. Returns `[pattern]` unchanged if `pattern` has no
    top-level alternation.

    Raises:
        ValueError: if `pattern` is not anchored with `^...$`.
    """
    if not (pattern.startswith('^') and pattern.endswith('$')):
        raise ValueError(
            f'count_strings requires an anchored pattern (^...$): '
            f'{pattern!r}'
        )
    body = pattern[1:-1]
    if body.startswith('(') and _matching_paren(body, 0) == len(body) - 1:
        body = body[1:-1]
    parts = _split_top_level(body, '|')
    if len(parts) == 1:
        return [pattern]
    return ['^%s$' % p for p in parts]


def _matching_paren(s, i):
    """Return the index of the `)` matching the `(` at `s[i]`,
    treating bracket expressions and escapes as opaque units.
    """
    depth = 0
    j, n = i, len(s)
    while j < n:
        c = s[j]
        if c == '\\':
            j += 2
        elif c == '[':
            j = _charclass_end(s, j, s)
        elif c == '(':
            depth += 1
            j += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return j
            j += 1
        else:
            j += 1
    raise ValueError(f"unterminated '(' in pattern: {s!r}")


def _split_top_level(s, sep):
    """Split `s` on `sep`, ignoring any occurrence nested inside a
    bracket expression, a parenthesised group, or an escape.
    """
    parts = []
    depth = 0
    start = 0
    i, n = 0, len(s)
    while i < n:
        c = s[i]
        if c == '\\':
            i += 2
        elif c == '[':
            i = _charclass_end(s, i, s)
        elif c == '(':
            depth += 1
            i += 1
        elif c == ')':
            depth -= 1
            i += 1
        elif c == sep and depth == 0:
            parts.append(s[start:i])
            i += 1
            start = i
        else:
            i += 1
    parts.append(s[start:])
    return parts


def _validate_pattern(pattern):
    """Check that `pattern` is a pattern `count_strings_no_alt` can
    handle: a valid regex that is anchored, alternation-free, and
    uses only known escapes.

    Raises:
        ValueError: if the pattern is not supported.
    """
    try:
        re.compile(pattern)
    except re.error as e:
        raise ValueError(f'not a valid regex: {pattern!r} ({e})')
    if not (pattern.startswith('^') and pattern.endswith('$')):
        raise ValueError(
            f'count_strings_no_alt requires an anchored pattern '
            f'(^...$): {pattern!r}'
        )
    body = pattern[1:-1]
    i, n = 0, len(body)
    while i < n:
        c = body[i]
        if c == '\\':
            if i + 1 >= n:
                raise ValueError(
                    f'trailing backslash in pattern: {pattern!r}'
                )
            e = body[i + 1]
            if e not in CLASS_ESCAPES and e not in LITERAL_ESCAPES:
                raise ValueError(
                    f'unsupported escape \\{e} in pattern: {pattern!r}'
                )
            i += 2
        elif c == '[':
            i = _charclass_end(body, i, pattern)
        elif c in '()|':
            raise ValueError(
                'count_strings_no_alt does not support alternation '
                f'or groups: {pattern!r}'
            )
        else:
            i += 1


def _charclass_end(body, i, pattern):
    """Return the index just past the closing `]` of the bracket
    expression starting at `body[i]` (which must be `'['`).
    """
    n = len(body)
    j = i + 1
    if j < n and body[j] == '^':
        j += 1
    if j < n and body[j] == ']':  # literal ']' as first character
        j += 1
    while j < n and body[j] != ']':
        j += 2 if body[j] == '\\' else 1
    if j >= n:
        raise ValueError(f"unterminated '[' in pattern: {pattern!r}")
    return j + 1


def _parse_pattern(pattern, max_plus):
    """Split an anchored, alternation-free regex into a list of
    `(kind, value, repeat)` atoms, where `kind` is `'charclass'`
    for a character class/escape/dot and `'literal'` for a single
    literal character, and `repeat` is a `Repeat`.

    Assumes `pattern` has already passed `_validate_pattern`.
    """
    body = pattern[1:-1]
    i = 0
    n = len(body)
    atoms = []
    while i < n:
        c = body[i]
        if c == '\\':
            atom = body[i : i + 2]
            i += 2
            if atom[1] in CLASS_ESCAPES:
                kind, value = 'charclass', atom
            else:
                kind, value = 'literal', atom[1]
        elif c == '[':
            j = _charclass_end(body, i, pattern)
            kind, value = 'charclass', body[i:j]
            i = j
        elif c == '.':
            kind, value = 'charclass', '.'
            i += 1
        else:
            kind, value = 'literal', c
            i += 1
        repeat, i = _parse_quantifier(body, i, max_plus)
        atoms.append((kind, value, repeat))
    return atoms


def _parse_quantifier(body, i, max_plus):
    """Parse an optional quantifier starting at `body[i]`.

    Returns `(repeat, i)`: the atom's `Repeat` range, and the
    index immediately after the quantifier (unchanged if there is
    none).
    """
    n = len(body)
    if i >= n:
        return Repeat(1, 1), i
    c = body[i]
    if c == '?':
        return Repeat(0, 1), i + 1
    if c == '*':
        return Repeat(0, max_plus), i + 1
    if c == '+':
        return Repeat(1, max_plus), i + 1
    if c == '{':
        j = body.index('}', i)
        spec = body[i + 1 : j]
        if ',' in spec:
            m_s, M_s = spec.split(',')
            m = int(m_s) if m_s else 0
            M = int(M_s) if M_s else max(m, max_plus)
        else:
            m = M = int(spec)
        return Repeat(m, M), j + 1
    return Repeat(1, 1), i


def _atom_size(kind, value, alphabet, pattern):
    """Return the number of characters in `alphabet` (a
    `ResolvedAlphabet`) admitted by a single parsed atom (as
    returned by `_parse_pattern`).

    Raises:
        ValueError: if the atom explicitly references a character
            (a literal, a bracket member/range, or a canonical
            escape member) that isn't in `alphabet`.
    """
    if kind == 'literal':
        _check_subset(value, alphabet, pattern)
        return 1
    if value == '.' or value[0] == '\\':
        code = value if value == '.' else value[1]
        return _escape_size(code, alphabet, pattern)
    negated, members = _charclass_members(value)
    _check_subset(members, alphabet, pattern)
    return alphabet.size - len(members) if negated else len(members)


def _escape_size(code, alphabet, pattern):
    """Return the number of characters in `alphabet` (a
    `ResolvedAlphabet`) matched by `.` (`code='.'`) or a
    `\\d`/`\\D`/`\\w`/`\\W`/`\\s`/`\\S` shorthand escape (`code`
    one of `'dDwWsS'`).

    `.` matches the whole alphabet, except `\\n` (matching Python's
    `re` semantics without `re.DOTALL`, which we never use).

    `\\d` and `\\w` behave like their expanded bracket-class
    equivalents (`[0-9]`, `[A-Za-z0-9_]`): fixed sets (see
    `CANONICAL_CLASSES`) that must be fully present in `alphabet`.

    `\\s` is treated more loosely: whitespace is a soft concept,
    so only whichever of its canonical members are actually in
    `alphabet` count, and it's rejected only if none of them are.

    Upper-case negations are the complement of whatever their
    lower-case counterpart resolved to, within `alphabet`.

    Raises:
        ValueError: for `\\d`/`\\w`, if any canonical member is
            missing from `alphabet`; for `\\s`, only if none of
            its canonical members are in `alphabet` at all.
    """
    if code == '.':
        return alphabet.size - (1 if alphabet.pattern.fullmatch('\n') else 0)
    members = CANONICAL_CLASSES[code.lower()]
    if code.lower() == 's':
        present = _intersect_alphabet(members, alphabet, pattern)
    else:
        _check_subset(members, alphabet, pattern)
        present = members
    if code.isupper():
        return alphabet.size - len(present)
    return len(present)


def _intersect_alphabet(members, alphabet, pattern):
    """Return the subset of `members` that `alphabet.pattern`
    matches.

    Raises:
        ValueError: if none of `members` is in `alphabet` --
            i.e. the canonical class is entirely disjoint from
            `alphabet`, rather than merely a partial overlap.
    """
    present = frozenset(c for c in members if alphabet.pattern.fullmatch(c))
    if not present:
        raise ValueError(
            f'none of the canonical members {sorted(members)!r} are '
            f'in alphabet: {pattern!r}'
        )
    return present


def _check_subset(chars, alphabet, pattern):
    """Raise if any character in `chars` isn't matched by
    `alphabet.pattern` (a `ResolvedAlphabet`)."""
    extra = sorted(c for c in set(chars) if not alphabet.pattern.fullmatch(c))
    if extra:
        raise ValueError(
            f'pattern uses characters outside alphabet {extra!r}: '
            f'{pattern!r}'
        )


def _resolve_alphabet(alphabet):
    """Resolve `alphabet` (`None`, a bracket-expression string, or
    a plain string of characters) into a `ResolvedAlphabet`.

    Raises:
        ValueError: if `alphabet` is a negated character class
            (`'[^...]'`), which has no well-defined size on its
            own.
    """
    if alphabet is None:
        alphabet = Alphabets.ASCII
    spec = _alphabet_spec(alphabet)
    negated, ranges = _charclass_ranges(spec)
    if negated:
        raise ValueError(
            f'alphabet cannot be a negated character class: '
            f'{alphabet!r}'
        )
    size = sum(hi - lo + 1 for lo, hi in _merge_ranges(ranges))
    return ResolvedAlphabet(re.compile(spec), size)


def _alphabet_spec(alphabet):
    """Normalize `alphabet` into a canonical bracket-expression
    string: used as-is if it already is one (starts with `[` and
    spans the whole string), otherwise built from its characters.
    """
    if (
        alphabet.startswith('[')
        and _charclass_end(alphabet, 0, alphabet) == len(alphabet)
    ):
        return alphabet
    return '[%s]' % _escape_for_charclass(alphabet)


def _escape_for_charclass(chars):
    """Escape characters that are special inside a bracket
    expression (`]`, `^`, `-`, `\\`), for building one from a
    literal set of characters.
    """
    specials = set('\\]^-')
    return ''.join(
        ('\\' + c if c in specials else c) for c in sorted(set(chars))
    )


def _charclass_members(value):
    """Parse a bracket expression such as `'[a-z0-9_]'` or
    `'[^abc]'` into `(negated, members)`, where `members` is the
    explicit, expanded set of characters listed (individually or
    via ranges) -- the characters the class matches if not
    negated, or the characters it excludes if negated.
    """
    negated, ranges = _charclass_ranges(value)
    members = set()
    for lo, hi in ranges:
        members.update(chr(cp) for cp in range(lo, hi + 1))
    return negated, frozenset(members)


def _charclass_ranges(value):
    """Parse a bracket expression such as `'[a-z0-9_]'` or
    `'[^abc]'` into `(negated, ranges)`, where `ranges` is a list
    of `(lo, hi)` codepoint tuples -- the range endpoints listed
    (individually or via `x-y` ranges) -- without expanding them
    into individual characters.
    """
    body = value[1:-1]  # strip outer '[' and ']'
    negated = body.startswith('^')
    if negated:
        body = body[1:]
    ranges = []
    i, n = 0, len(body)
    while i < n:
        if body[i] == '\\':
            c, i = body[i + 1], i + 2
        else:
            c, i = body[i], i + 1
        if i < n and body[i] == '-' and i + 1 < n:
            i += 1  # skip '-'
            if body[i] == '\\':
                d, i = body[i + 1], i + 2
            else:
                d, i = body[i], i + 1
            ranges.append((ord(c), ord(d)))
        else:
            ranges.append((ord(c), ord(c)))
    return negated, ranges


def _merge_ranges(ranges):
    """Merge overlapping or adjacent `(lo, hi)` codepoint ranges,
    so that summing their sizes doesn't double-count.
    """
    merged = []
    for lo, hi in sorted(ranges):
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))
    return merged


def _rate(numerator, denominator):
    """Compute `numerator / denominator` as a rate, treating the
    degenerate cases sensibly rather than raising:

    - `0/0` is `0.0` (no false results occurred, regardless of
      whether there was theoretically room for any).
    - a positive numerator over a zero denominator is
      `float('inf')` (the regex admits things entirely outside
      what the assumed universe accounts for).
    """
    if denominator == 0:
        return 0.0 if numerator == 0 else float('inf')
    return numerator / denominator


class RexMetrics:
    """
    Quality metrics for a single regex, scored against a set of
    positive examples.

    Args:
        len (int): length of the regex string.
        fp (int or CountRange): false positive count -- strings the
            regex admits beyond the true positives it actually
            matches. A `CountRange` if the pattern has alternation
            with genuine overlap uncertainty, an `int` otherwise
            (see `count_strings`).
        fn (int): false negative count -- true positives the regex
            fails to match. Always exact (found by directly testing
            the compiled pattern against the real positives), never
            a range, regardless of alternation.
        fpr (float or CountRange): false positive rate (`fp`
            divided by the number of "invalid" strings in the
            universe) -- a `CountRange` of rates iff `fp` is a
            `CountRange`. Optional; `eq()` only compares it when
            given (on either side).
        fnr (float): false negative rate (`fn / n_positives`).
            Optional, compared by `eq()` only when given.
        universe (int): size of the assumed universe of possible
            strings. Not itself a quality measure (it's context,
            not a property of the regex), so `eq()` never compares
            it directly -- but uses it to derive a default `tol`
            when one isn't given explicitly.
    """

    def __init__(self, len, fp, fn, fpr=None, fnr=None, universe=None):
        self.len = len
        self.fp = fp
        self.fn = fn
        self.fpr = fpr
        self.fnr = fnr
        self.universe = universe

    def eq(self, other, tol=None):
        """Compare quality against `other`.

        `len`, `fp` and `fn` are always compared exactly (`fp`
        may be an `int` or a `CountRange`; plain `==` already
        does the right thing either way, including correctly
        rejecting a mismatch between the two). `fpr` and `fnr`
        are compared (within `tol`) only if `other` specifies
        them (is not `None`) -- letting `other` be a
        partially-specified expected value. Each is compared as a
        single float, or component-wise if both sides are a
        `CountRange` of rates; a scalar vs. `CountRange` mismatch
        is simply unequal (this is a convenience for readable
        tests, not a general-purpose comparison, so callers are
        expected to know which shape to expect).

        `tol` defaults to the smaller of `1/(10*universe)` over
        whichever of `self`/`other` have a `universe` set, or
        `0.0` (exact comparison) if neither does.

        Returns:
            bool
        """
        if self.len != other.len or self.fp != other.fp:
            return False
        if self.fn != other.fn:
            return False
        if tol is None:
            tol = _default_tol(self, other)
        for attr in ('fpr', 'fnr'):
            expected = getattr(other, attr)
            if expected is None:
                continue
            actual = getattr(self, attr)
            if not _rates_close(actual, expected, tol):
                return False
        return True


def _rates_close(actual, expected, tol):
    """Compare two rates (each a single `float` or a `CountRange`
    of rates) within `tol`. A scalar/`CountRange` mismatch is
    always unequal.
    """
    if isinstance(actual, CountRange) != isinstance(expected, CountRange):
        return False
    if isinstance(actual, CountRange):
        return math.isclose(
            actual.lower, expected.lower, abs_tol=tol
        ) and math.isclose(actual.upper, expected.upper, abs_tol=tol)
    return actual is not None and math.isclose(
        actual, expected, abs_tol=tol
    )


def _default_tol(a, b):
    """Derive a default tolerance for `RexMetrics.eq()` from
    whichever of `a`/`b` have a `universe` set: the smaller of
    `1/(10*universe)` over those that do, or `0.0` if neither does.
    """
    candidates = [
        1 / (10 * m.universe)
        for m in (a, b)
        if m.universe is not None and m.universe > 0
    ]
    return min(candidates) if candidates else 0.0


class ConcreteRexMetric:
    """
    A reusable scorer bound to a fixed set of positive examples,
    alphabet and length range. Call `evaluate(pattern)` once per
    candidate regex to score it against them.
    """

    def __init__(
        self, all_positives, alphabet=None, min_length=None,
        max_length=None,
    ):
        self.all_positives = all_positives
        self.alphabet = alphabet
        self.n_positives = len(all_positives)
        lengths = [len(s) for s in all_positives]
        self.min_length = min(lengths) if min_length is None else min_length
        self.max_length = max(lengths) if max_length is None else max_length
        resolved = _resolve_alphabet(alphabet)
        self.universe = sum(
            resolved.size**k
            for k in range(self.min_length, self.max_length + 1)
        )

    def evaluate(self, pattern, max_plus=DEFAULT_MAX_PLUS):
        """Score `pattern` against `self.all_positives`.

        `pattern` may contain alternation: `count_strings` returns
        an `int` when the admitted count is exact, or a
        `CountRange` when alternation leaves genuine overlap
        uncertainty, and `fp`/`fpr` follow suit.

        `max_plus` is passed through to `count_strings`, to size
        unbounded quantifiers (`+`, `*`, open `{m,}`); it defaults
        to `DEFAULT_MAX_PLUS` (5), which may not reach `self`'s
        actual `max_length` for patterns using them.

        Returns:
            RexMetrics
        """
        compiled = re.compile(pattern)
        fn = sum(
            1 for s in self.all_positives if not compiled.fullmatch(s)
        )
        fnr = _rate(fn, self.n_positives)
        admitted = count_strings(
            pattern, max_plus=max_plus, alphabet=self.alphabet
        )
        n_true_matched = self.n_positives - fn
        fp_denominator = self.universe - self.n_positives
        # fp can never legitimately exceed fp_denominator (a false
        # positive is, by definition, one of the actual negatives,
        # so fpr = fp / (fp + TN) <= 1 always). count_strings's
        # approximations (unbounded quantifiers reaching past
        # max_length, or alternation's sum-as-upper-bound when
        # branches overlap) can overshoot that bound; clamping
        # enforces the invariant rather than reporting fpr > 1.
        # When fp_denominator is 0 (no room for any false
        # positives at all), that's a special case handled by
        # _rate itself (0/0 -> 0.0, positive/0 -> inf) -- clamping
        # doesn't apply there.
        if isinstance(admitted, CountRange):
            fp = CountRange(
                admitted.lower - n_true_matched,
                admitted.upper - n_true_matched,
            )
            if fp_denominator > 0:
                fp = CountRange(
                    min(fp.lower, fp_denominator),
                    min(fp.upper, fp_denominator),
                )
            fpr = CountRange(
                _rate(fp.lower, fp_denominator),
                _rate(fp.upper, fp_denominator),
            )
        else:
            fp = admitted - n_true_matched
            if fp_denominator > 0:
                fp = min(fp, fp_denominator)
            fpr = _rate(fp, fp_denominator)
        return RexMetrics(
            len=len(pattern), fp=fp, fn=fn, fpr=fpr, fnr=fnr,
            universe=self.universe,
        )
