#!/bin/sh

function runTests(){
    # python testtdda.py
    python3 testtdda.py
}

MIRODIR=`miro -c config basedir`
. $MIRODIR/pushv-common.sh tdda
echo "Go to readthedocs.io, build the doc and set this as the default."





