TDDA_MAJOR_VERSION = 3
TDDA_MINOR_VERSION = 0
TDDA_EDIT = 0
TDDA_VERSION_QUALIFIER = 'rc1'
TDDA_VERSION = '%d.%d.%02d%s' % (
    TDDA_MAJOR_VERSION,
    TDDA_MINOR_VERSION,
    TDDA_EDIT,
    TDDA_VERSION_QUALIFIER,
)
version = TDDA_VERSION

if __name__ == '__main__':
    print(version)
